// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial

package com.mengpaw.core.namespace.sys

/**
 * sys.* 命令中文同义词表 — 补 BM25 搜索索引用 (kernel 静态种子无 sys, 反射 Android API)。
 * 缺失项回退命令名分词。从 SysExecutor 拆出以守单文件 ≤400 行红线。
 */
internal val SYS_KEYWORDS_ZH: Map<String, List<String>> = mapOf(
    "device" to listOf("设备", "型号", "厂商", "系统", "安卓"),
    "battery" to listOf("电量", "电池", "充电", "温度", "续航"),
    "power" to listOf("电源", "省电", "功耗", "充电"),
    "power.save" to listOf("省电", "省电模式", "功耗", "节能"),
    "network" to listOf("网络", "信号", "数据", "蜂窝"),
    "wifi" to listOf("WIFI", "无线", "热点"),
    "wifi.enable" to listOf("开WIFI", "关WIFI", "切换无线"),
    "wifi.scan" to listOf("扫描WiFi", "热点扫描", "附近WiFi"),
    "bluetooth" to listOf("蓝牙", "配对"),
    "location" to listOf("定位", "位置", "GPS", "坐标"),
    "cpu" to listOf("CPU", "处理器", "占用", "性能"),
    "memory" to listOf("内存", "RAM", "占用"),
    "storage" to listOf("存储", "空间", "磁盘"),
    "camera" to listOf("相机", "摄像头", "拍照"),
    "sensors" to listOf("传感器", "陀螺仪", "加速计"),
    "display" to listOf("屏幕", "分辨率", "亮度", "显示"),
    "telephony" to listOf("电话", "运营商", "SIM", "信号"),
    "screen.on" to listOf("亮屏", "唤醒屏幕", "开屏"),
    "screen.off" to listOf("熄屏", "关屏", "锁屏"),
    "screen.brightness" to listOf("亮度", "调亮度", "屏幕亮度"),
    "volume" to listOf("音量", "声音", "媒体音量"),
    "volume.set" to listOf("调音量", "设置音量", "静音"),
    "vibrate" to listOf("震动", "振动", "马达"),
    "ringtone.play" to listOf("铃声", "播放铃声", "响铃"),
    "apps" to listOf("应用", "应用列表", "已安装", "APP"),
    "app.launch" to listOf("打开应用", "启动", "启动应用", "运行"),
    "app.uninstall" to listOf("卸载应用", "卸载"),
    "app.info" to listOf("应用详情", "应用信息"),
    "browser.open" to listOf("打开浏览器", "浏览器", "网页", "唤起"),
    "clipboard" to listOf("剪贴板", "复制", "粘贴", "内容"),
    "clipboard.set" to listOf("写剪贴板", "复制内容"),
    "intent.open" to listOf("打开链接", "intent", "跳转", "协议"),
    "intent.share" to listOf("分享", "分享文本", "转发"),
    "intent.view" to listOf("查看", "打开文件"),
    "notification.id" to listOf("通知ID", "通知标识"),
    "notification.send" to listOf("发通知", "通知", "推送消息"),
    "notification.cancel" to listOf("取消通知", "清除通知"),
    "notification.list" to listOf("通知列表", "查看通知", "通知内容"),
    "alarm.set" to listOf("闹钟", "定时提醒", "设置闹钟"),
    "permission.list" to listOf("权限列表", "权限", "已授权"),
    "permission.check" to listOf("检查权限", "权限状态"),
    "permission.request" to listOf("申请权限", "请求权限", "授权"),
    "overlay.show" to listOf("悬浮窗", "显示悬浮窗", "弹窗"),
    "overlay.hide" to listOf("隐藏悬浮窗", "关闭悬浮窗"),
    "overlay.update" to listOf("更新悬浮窗", "刷新悬浮窗"),
    "calendar.add" to listOf("日历", "添加事件", "日程", "提醒"),
    "calendar.list" to listOf("日历列表", "日程", "查看事件"),
    "calendar.delete" to listOf("删除事件", "删除日程"),
    "calendar.calendars" to listOf("日历账户", "日历列表"),
    "screenshot" to listOf("截图", "截屏", "屏幕快照"),
    "screenrecord.start" to listOf("录屏", "屏幕录制", "录视频", "开始录屏"),
    "screenrecord.stop" to listOf("停止录屏", "结束录屏", "保存视频"),
    "camera.photo" to listOf("拍照", "拍摄", "照片", "相机拍照"),
    "dialog.confirm" to listOf("确认对话框", "确认弹窗", "询问确认"),
    "dialog.text" to listOf("输入对话框", "文本输入", "询问输入"),
    "dialog.radio" to listOf("单选", "单选对话框", "选择题"),
    "dialog.checkbox" to listOf("多选", "复选框", "多选题"),
    "dialog.spinner" to listOf("下拉选择", "选择对话框"),
    "dialog.sheet" to listOf("底部弹窗", "操作列表", "选项列表"),
    "dialog.date" to listOf("日期选择", "日期对话框", "选日期"),
    "dialog.time" to listOf("时间选择", "时间对话框", "选时间"),
    "dialog.counter" to listOf("数字选择", "计数器", "选数值"),
    "dialog.color" to listOf("颜色选择", "取色", "选颜色"),
    "dialog.speech" to listOf("语音输入", "语音对话框", "说话输入"),
    "tts.speak" to listOf("朗读", "语音合成", "TTS", "读出来"),
    "tts.engines" to listOf("语音引擎", "TTS引擎", "语音合成引擎"),
    "stt.listen" to listOf("语音转文字", "听写", "语音识别", "转写"),
    "mic.record" to listOf("录音", "麦克风", "录制音频"),
    "mic.stop" to listOf("停止录音", "结束录音"),
    "torch.on" to listOf("开手电筒", "手电筒", "闪光灯"),
    "torch.off" to listOf("关手电筒", "关闭闪光灯"),
    "contacts.list" to listOf("联系人", "通讯录", "电话本"),
    "sms.send" to listOf("发短信", "发送短信", "短信"),
    "sms.list" to listOf("短信列表", "收件箱", "查看短信"),
    "calllog.list" to listOf("通话记录", "通话历史", "呼叫记录"),
    "phone.call" to listOf("拨打电话", "拨号", "打电话"),
    "download" to listOf("下载", "下载文件", "下载任务"),
    "wallpaper.set" to listOf("壁纸", "设置壁纸", "换壁纸"),
    "toast" to listOf("提示", "气泡提示", "toast"),
    "wakelock.acquire" to listOf("唤醒锁", "保持唤醒", "不熄屏"),
    "wakelock.release" to listOf("释放唤醒锁", "恢复熄屏"),
    "ir.transmit" to listOf("红外", "红外遥控", "发射红外"),
    "usb.list" to listOf("USB设备", "USB列表", "外设"),
    "usb.request" to listOf("USB授权", "连接USB", "USB权限")
)
