// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial

package com.mengpaw.shell.ui.localization

/**
 * Localized strings for the MengPaw UI.
 * Switch between Chinese (zh) and English (en) with one click.
 */
class AppStrings {

    // App
    var isChinese: Boolean = false
    var appName: String = ""
    var settings: String = ""
    var back: String = ""

    // Main Screen
    var systemBanner: String = ""
    var inputPlaceholder: String = ""
    var commandOutputLabel: String = ""
    var commandFailedLabel: String = ""
    var thinking: String = ""
    var agentLabel: String = ""
    var stop: String = ""
    var send: String = ""

    // Voice input (v0.33.0+)
    var voiceInput: String = ""
    var voiceReleaseToSend: String = ""
    var voiceSlideToCancel: String = ""
    var voiceTooShort: String = ""
    var voicePermissionDenied: String = ""

    // Settings - LLM Provider
    var llmProvider: String = ""
    var apiEndpoint: String = ""
    var apiKey: String = ""
    var apiKeyShow: String = ""
    var apiKeyHide: String = ""
    var model: String = ""

    // Settings - Agent
    var agent: String = ""
    var maxSteps: String = ""
    var maxStepsDesc: String = ""
    var llmConcurrency: String = ""
    var llmConcurrencyDesc: String = ""

    // Settings - Appearance
    var appearance: String = ""
    var darkTheme: String = ""
    var darkThemeDesc: String = ""
    var language: String = ""
    var languageDesc: String = ""
    var languageZh: String = ""
    var languageEn: String = ""

    // Settings - Agent Language
    var agentLanguage: String = ""
    var agentLanguageDesc: String = ""
    var agentLanguageFollowUi: String = ""
    var agentLanguageChinese: String = ""
    var agentLanguageEnglish: String = ""

    // Expand panel
    var expandFileSection: String = ""
    var expandModeSection: String = ""
    var expandPluginSection: String = ""
    var filePickImage: String = ""
    var filePickDocument: String = ""
    var filePickFile: String = ""
    var filePickCamera: String = ""
    var dragHint: String = ""

    // Execution mode tags
    var tagModeResearch: String = ""
    var tagModeTranslate: String = ""
    var tagModeSilent: String = ""
    var tagDismiss: String = ""
    var mentionHint: String = ""

    // Mode-specific placeholders
    var placeholderSwarm: String = ""
    var placeholderFleet: String = ""
    var placeholderResearch: String = ""
    var placeholderTranslate: String = ""
    var placeholderSilent: String = ""

    // Settings - Device guides (USB debugging / Root / Accessibility)
    var guideSection: String = ""
    var guideSectionDesc: String = ""
    var guideUsb: String = ""
    var guideUsbDesc: String = ""
    var guideRoot: String = ""
    var guideRootDesc: String = ""
    var guideAccessibility: String = ""
    var guideAccessibilityDesc: String = ""
    var guideClose: String = ""

    // Settings - About
    var about: String = ""
    var version: String = ""
    var core: String = ""
    var design: String = ""
    var resetDefaults: String = ""

    // Sidebar
    var sidebarAgents: String = ""
    var sidebarCurrent: String = ""
    var sidebarFeatures: String = ""
    var sidebarFrameworkDirectory: String = ""
    var sidebarFrameworkStatus: String = ""
    var sidebarNoFriends: String = ""
    var sidebarPlugins: String = ""
    var sidebarSettings: String = ""

    // General
    var cancel: String = ""
    var delete: String = ""

    // Settings - System
    var systemAttribution: String = ""
    var systemAttributionDesc: String = ""
    var systemBackground: String = ""
    var systemBackgroundMode: String = ""
    var systemBackgroundPowerSaver: String = ""
    var systemBackgroundPowerSaverDesc: String = ""
    var systemBatteryIgnored: String = ""
    var systemBatteryIgnoredDesc: String = ""
    var systemBatteryNotIgnored: String = ""
    var systemBatteryNotIgnoredDesc: String = ""
    var systemCacheSaved: String = ""
    var systemContactUs: String = ""
    var systemCopyright: String = ""
    var systemCopyrightDesc: String = ""
    var systemDaily: String = ""
    var systemEstimatedSavings: String = ""
    var systemGoToBatterySettings: String = ""
    var systemLegalContact: String = ""
    var systemLicense: String = ""
    var systemMonthly: String = ""
    var systemNoTokenData: String = ""
    var systemTimezone: String = ""
    var systemTimezoneAuto: String = ""
    var systemTimezoneShanghai: String = ""
    var systemTokenStats: String = ""
    var systemTotalUsage: String = ""
    var systemWeekly: String = ""

    // Settings - Agent
    var agentAddHumanTouch: String = ""
    var agentAddScheduled: String = ""
    var agentApiReturnedModels: String = ""
    var agentFromGlobalPool: String = ""
    var agentFromSkillPool: String = ""
    var agentInstallHelp: String = ""
    var agentLastFired: String = ""
    var agentLoopMode: String = ""
    var agentLoopModeDesc: String = ""
    var agentNoProvider: String = ""
    var agentNoSkills: String = ""
    var agentNoTriggers: String = ""
    var agentParams: String = ""
    var agentPlugins: String = ""
    var agentProviderModel: String = ""
    var agentRefreshFileList: String = ""
    var agentRefreshModels: String = ""
    var agentRemainingCount: String = ""
    var agentSelectModel: String = ""
    var agentShellTimeout: String = ""
    var agentShellTimeoutDesc: String = ""
    var agentSkills: String = ""
    var agentSkillPool: String = ""
    var agentTools: String = ""
    var agentTriggerHuman: String = ""
    var agentTriggers: String = ""
    var agentTriggerScheduled: String = ""
    var agentWorkspaceFiles: String = ""
    var agentAutoTranslate: String = ""
    var agentAutoTranslateDesc: String = ""
    // Agent 引导进度 (P2-13)
    var agentBoostPanel: String = ""
    var agentBoostPanelDesc: String = ""
    var agentBoostDone: String = ""
    var agentBoostProgress: String = ""
    var agentBoostItemIdentity: String = ""
    var agentBoostItemAvatar: String = ""
    var agentBoostItemTheme: String = ""
    var agentBoostItemSoul: String = ""
    var agentBoostHint: String = ""

    // Settings - Framework
    var frameworkAddProvider: String = ""
    var frameworkApiProvider: String = ""
    var frameworkCollapseList: String = ""
    var frameworkContextStrategy: String = ""
    var frameworkContextStrategyDesc: String = ""
    var frameworkEditConnection: String = ""
    var frameworkGlobalPlugins: String = ""
    var frameworkGlobalSkills: String = ""
    var frameworkGlobalTools: String = ""
    var frameworkMemoryBackend: String = ""
    var frameworkMemoryBackendDesc: String = ""
    var frameworkMemoryManagement: String = ""
    var frameworkNewConnection: String = ""
    var frameworkPluginManagement: String = ""
    var frameworkPluginManagementDesc: String = ""
    var frameworkProviderLabel: String = ""
    var frameworkSaveConnection: String = ""
    var frameworkTestConnection: String = ""
    var frameworkTestingConnection: String = ""

    // Settings - Sidebar tabs
    var sidebarSettingsAgent: String = ""
    var sidebarSettingsFramework: String = ""
    var sidebarSettingsSystem: String = ""

    // Security
    var securityAgentDocs: String = ""
    var securityFingerprint: String = ""
    var securityFileIntegrity: String = ""
    var securityFileIntegrityDesc: String = ""
    var securityKernelDir: String = ""
    var securityKernelIntegrity: String = ""
    var securityKernelIntegrityDesc: String = ""
    var securityKeyStore: String = ""
    var securityNoTrusted: String = ""
    var securityPluginCache: String = ""
    var securityPluginIntegrity: String = ""
    var securityPluginIntegrityDesc: String = ""
    var securityProtectedDirs: String = ""
    var securityRules: String = ""
    var securityTrusted: String = ""
    var securityTrustedCount: String = ""
    var securityTrustedFramework: String = ""

    // ── 插件市场 / 详情（英文化补全）──
    var pluginMarketTitle: String = ""
    var forceRefresh: String = ""
    var marketTab: String = ""
    var installedTab: String = ""
    var noPluginsAvailable: String = ""
    var noInstalledPlugins: String = ""
    var refreshHint: String = ""
    var availablePrefix: String = ""
    var installedPrefix: String = ""
    var activePrefix: String = ""
    var builtinBadge: String = ""
    var embeddedBadge: String = ""
    var activeBadge: String = ""
    var disabledBadge: String = ""
    var notPublishedBadge: String = ""
    var uninstall: String = ""
    var install: String = ""
    var verifying: String = ""
    var installedBadge: String = ""
    var failedBadge: String = ""
    var retry: String = ""
    var pluginNotFound: String = ""
    var notInstalledBadge: String = ""
    var typePrefix: String = ""
    var commandsLabel: String = ""
    var permissionsLabel: String = ""
    var enable: String = ""
    var disable: String = ""
    var installPlugin: String = ""
    var errorPrefix: String = ""
    // ── 触发器对话框 ──
    var cronTitle: String = ""
    var cronExpression: String = ""
    var cronPlaceholder: String = ""
    var cronHint: String = ""
    var actionLabel: String = ""
    var actionPlaceholder: String = ""
    var cronTip: String = ""
    var add: String = ""
    var scheduleTitle: String = ""
    var scheduleParams: String = ""
    var scheduleParamsPlaceholder: String = ""
    var scheduleFormatHint: String = ""
    var scheduleTip: String = ""
    // ── 设置卡片/Agent 设置/框架设置剩余硬编码 ──
    var noEntries: String = ""
    var noDocs: String = ""
    var agentToolsDesc: String = ""
    var noToolsConfigured: String = ""
    var agentSkillsDesc: String = ""
    var noWorkspaceDocs: String = ""
    var deleteDoc: String = ""
    var deleteConfirm: String = ""
    var agentToolDeleteConfirm: String = ""
    var resetDoc: String = ""
    var resetConfirm: String = ""
    var openDoc: String = ""
    var editOpenFailed: String = ""
    var optimizedBadge: String = ""
    var apiReturned: String = ""
    // ── 枚举 label（中文名兜底用 enLabel 字段; 此处为共用 UI 文案）──
    var builtinCategory: String = ""
    var officialCategory: String = ""
    var customCategory: String = ""
    var lightTheme: String = ""
    var systemTheme: String = ""
    var notifPersistent: String = ""
    var silentRunning: String = ""
    var foregroundOnly: String = ""
    var notifPersistentDesc: String = ""
    var silentRunningDesc: String = ""
    var foregroundOnlyDesc: String = ""
    var rolePlanner: String = ""
    var roleWorker: String = ""
    var roleVerifier: String = ""
    var roleSynthesizer: String = ""
    var roleWorkerAlt: String = ""

    // ── 侧边栏 Framework Status 三状态（标签 + 解释）──
    var frameworkStatusOnline: String = ""
    var frameworkStatusOnlineDesc: String = ""
    var frameworkStatusBusy: String = ""
    var frameworkStatusBusyDesc: String = ""
    var frameworkStatusOffline: String = ""
    var frameworkStatusOfflineDesc: String = ""

    // ── 卡片对话框共用 ──
    var close: String = ""
    var cardEdit: String = ""
    var cardSave: String = ""

    // ── 框架名片对话框 ──
    var frameworkCardTitle: String = ""
    var frameworkCardRemarkLabel: String = ""
    var frameworkCardVersion: String = ""
    var frameworkCardUntrusted: String = ""
    var frameworkCardHostedAgents: String = ""
    var frameworkCardDelete: String = ""
    var frameworkCardTrust: String = ""
    var frameworkCardUntwin: String = ""
    var frameworkCardUntrust: String = ""

    // ── 智能体名片对话框 ──
    var agentCardTitle: String = ""
    var agentCardNameLabel: String = ""
    var agentCardIntroLabel: String = ""
    var agentCardIntroField: String = ""
    var agentCardNoIntro: String = ""
    var agentCardWorkspaceFiles: String = ""
    var agentCardDelete: String = ""
    var agentCardDeleteTitle: String = ""
    var agentCardDeleteBody: String = ""
    var agentCardSwitch: String = ""

    // ── 新建智能体对话框 ──
    var newAgentTitle: String = ""
    var newAgentNameLabel: String = ""
    var newAgentNamePlaceholder: String = ""
    var newAgentFolderLabel: String = ""
    var newAgentFolderPlaceholder: String = ""
    var newAgentFolderHint: String = ""
    var newAgentIntroLabel: String = ""
    var newAgentIntroPlaceholder: String = ""
    var newAgentCreate: String = ""
    var newAgentDefaultName: String = ""

    // ── 添加框架对话框 ──
    var addFrameworkTitle: String = ""
    var addFrameworkType: String = ""
    var addFrameworkName: String = ""
    var addFrameworkNamePlaceholder: String = ""
    var addFrameworkAddress: String = ""
    var addFrameworkAddrPortPlaceholder: String = ""
    var addFrameworkAddrGenericPlaceholder: String = ""
    var addFrameworkScanLan: String = ""
    var addFrameworkDiscovered: String = ""
    // v0.35.1 框架发现流程调整: 配对请求-同意流程
    var pairPendingRequests: String = ""
    var pairNoPending: String = ""
    var pairAccept: String = ""
    var pairDecline: String = ""
    var pairAccepted: String = ""
    var pairDeclined: String = ""
    var pairRespondFailed: String = ""
    var pairScanEmpty: String = ""
    var pairScanHint: String = ""
    var pairRequestSent: String = ""
    var pairRequestFailed: String = ""
    var pairClearProcessed: String = ""
    var pairManualAdd: String = ""
    var pairAddedLocal: String = ""
    var frameworkPairRequestTitle: String = ""
    var pairRequestBody: String = ""
    var pairRequestHint: String = ""
    var pairRequestLater: String = ""
    var pairHistory: String = ""
    var pairHistoryEmpty: String = ""
    // v0.35.2 审查: 气泡图标操作行 / 输出目录区块 / 安全分级面板 / 权限引导 / 名片标签
    var bubbleCopy: String = ""
    var bubbleBigBang: String = ""
    var bubbleQuote: String = ""
    var bubbleSaveImages: String = ""
    var bubbleMarkImage: String = ""
    var bubbleShare: String = ""
    var bubbleRetract: String = ""
    var bubbleShareTo: String = ""
    var outputDirTitle: String = ""
    var outputDirCurrent: String = ""
    var outputDirUnwritable: String = ""
    var outputDirGrant: String = ""
    var outputPermissionTitle: String = ""
    var outputPermissionBody: String = ""
    var outputPermissionGrant: String = ""
    var outputPermissionLater: String = ""
    var permissionLevelTitle: String = ""
    var permissionStandard: String = ""
    var permissionTrusted: String = ""
    var permissionStandardDesc: String = ""
    var permissionTrustedDesc: String = ""
    var permissionLow: String = ""
    var permissionMidStandard: String = ""
    var permissionMidTrusted: String = ""
    var permissionHigh: String = ""
    var frameworkIdentityLabel: String = ""
    var frameworkIdentityDefaultPlaceholder: String = ""
    var frameworkUnknown: String = ""

    // ── 记忆孪生配对（侧边栏弹窗）──
    var twinRequestTitle: String = ""
    var twinRequestWarning: String = ""
    var twinRequestDevice: String = ""
    var twinRequestModel: String = ""
    var twinRequestAgreeDesc: String = ""
    var twinRequestAgree: String = ""
    var twinRequestDisagree: String = ""
    var twinVerifyTitle: String = ""
    var twinVerifyDesc: String = ""
    var twinVerifyPeer: String = ""
    var twinVerifyWarning: String = ""
    var twinVerifyConfirm: String = ""
    var twinConfirmTitle: String = ""
    var twinConfirmIntro: String = ""
    var twinConfirmWarning: String = ""
    var twinConfirmAction: String = ""
    var twinPairedToast: String = ""
    var unknown: String = ""

    // ── 工作区文件（memory 聚合条目合成文案）──
    var workspaceMemoryFolder: String = ""
    var workspaceMemoryHeader: String = ""
    var workspaceMemorySummary: String = ""
    var workspaceNotesFolder: String = ""
    var workspaceNotesSummary: String = ""
    var workspaceEvolutionFolder: String = ""
    var workspaceEvolutionSummary: String = ""
    var workspaceEmptyDoc: String = ""

    // ── 全局技能池面板 (来源标签/指定按钮) ──
    var skillSourceCore: String = ""
    var skillSourcePlugin: String = ""
    var skillPin: String = ""

    // ── 顶栏（会话模型标签）──
    var agentNoModel: String = ""
    var agentUnconfigured: String = ""
    var providerVolcano: String = ""
    var newSession: String = ""
    var history: String = ""

}
