// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial

package com.mengpaw.shell.ui.localization

/**
 * Chinese (Simplified) strings.
 */
val ChineseStrings = AppStrings().apply {

    isChinese = true
    appName = "MengPaw"
    settings = "设置 (Settings)"
    back = "返回"

    systemBanner = "Agent 已就绪。描述你想要完成的任务。"
    inputPlaceholder = "描述一个任务给 Agent..."
    commandOutputLabel = "命令输出"
    commandFailedLabel = "命令执行失败"
    thinking = "思考中 (Thinking)..."
    agentLabel = "Agent"
    stop = "停止"
    send = "发送"
    voiceInput = "语音输入"
    voiceReleaseToSend = "松开发送"
    voiceSlideToCancel = "上滑取消"
    voiceTooShort = "说话时间太短"
    voicePermissionDenied = "需要麦克风权限才能使用语音输入"

    llmProvider = "LLM 提供商 (Provider)"
    apiEndpoint = "API 地址 (Endpoint)"
    apiKey = "API 密钥 (Key)"
    apiKeyShow = "显示"
    apiKeyHide = "隐藏"
    model = "模型 (Model)"

    agent = "Agent"
    maxSteps = "最大步数 (Max Steps)"
    maxStepsDesc = "ReAct 循环最大迭代次数"
    llmConcurrency = "LLM 并发上限"
    llmConcurrencyDesc = "同时进行的 LLM API 调用数量上限 (1-50)"
    agentAutoTranslate = "自动翻译（美系模型）"
    agentAutoTranslateDesc = "将中文任务译为英文发给 OpenAI/Grok/Claude 系模型，回复再译回中文。默认关闭，仅在您主动开启时启用"

    appearance = "外观"
    darkTheme = "深色主题 (Dark Theme)"
    darkThemeDesc = "亮色 / 暗色 / 跟随系统"
    language = "语言 (Language)"
    languageDesc = "切换界面语言"
    languageZh = "中文"
    languageEn = "English"

    agentLanguage = "Agent 语言"
    agentLanguageDesc = "控制 Agent 思考和输出的语言"
    agentLanguageFollowUi = "跟随界面"
    agentLanguageChinese = "中文"
    agentLanguageEnglish = "English"

    expandFileSection = "文件提交"
    expandModeSection = "执行模式"
    expandPluginSection = "插件工具"
    filePickImage = "图片"
    filePickDocument = "文档"
    filePickFile = "文件"
    filePickCamera = "拍照"
    dragHint = "长按拖拽排序"

    tagModeResearch = "/Research"
    tagModeSilent = "/Silent"
    tagDismiss = "移除"
    mentionHint = "@智能体名称..."

    // v0.34.4: Swarm 是进化版的 Mission — 原 Mission 的拆解执行由 Swarm 承接
    placeholderSwarm = "输入需要火种模式并行拆解执行的任务（可混合不同模型）"
    placeholderFleet = "描述任务，Agent 编队跨设备/多框架协作执行..."
    placeholderResearch = "输入需要深度调研的课题，将进行多轮搜索与交叉验证"
    placeholderSilent = "输入后台静默执行的任务，完成后推送结果"

    about = "关于"
    version = "版本"
    core = "内核 (Core)"
    design = "设计 (Design)"
    resetDefaults = "恢复默认设置"

    // Sidebar
    sidebarAgents = "智能体"
    sidebarCurrent = "当前"
    sidebarFeatures = "功能"
    sidebarFrameworkDirectory = "框架通讯录"
    sidebarFrameworkStatus = "框架状态"
    sidebarNoFriends = "你的智能体还没有朋友"
    sidebarPlugins = "插件管理"
    sidebarSettings = "设置"

    // General
    cancel = "取消"
    delete = "删除"

    // Settings - System
    systemAttribution = "开源声明与致谢"
    systemAttributionDesc = "代码参考、灵感来源与许可合规"
    systemBackground = "后台运行"
    systemBackgroundMode = "后台运行策略"
    systemBackgroundPowerSaver = "后台省电模式"
    systemBackgroundPowerSaverDesc = "降低后台轮询频率和动画帧率，延长续航"
    systemBatteryIgnored = "已忽略电池优化"
    systemBatteryIgnoredDesc = "系统不会在息屏时限制后台运行"
    systemBatteryNotIgnored = "电池优化未忽略"
    systemBatteryNotIgnoredDesc = "点击跳转系统设置，关闭后可防止息屏限制"
    systemCacheSaved = "缓存节省"
    systemContactUs = "联系我们"
    systemCopyright = "版权声明"
    systemCopyrightDesc = "© 2026 深圳哇蓝文化科技有限公司"
    systemDaily = "每日"
    systemEstimatedSavings = "预估节省"
    systemGoToBatterySettings = "前往设置 →"
    systemLegalContact = "法律与联系"
    systemLicense = "许可证"
    systemMonthly = "每月"
    systemNoTokenData = "暂无 Token 用量数据。开始使用后自动记录。"
    systemTimezone = "时区"
    systemTimezoneAuto = "自动"
    systemTimezoneShanghai = "上海"
    systemTokenStats = "Token 用量统计"
    systemTotalUsage = "总用量"
    systemWeekly = "每周"
    autoUpdateTitle = "自动更新"
    autoUpdateClickHint = "打开设置自动检查更新 (GitHub/Gitee Releases)"
    autoUpdateChecking = "检查中..."
    autoUpdateDownload = "下载 APK"
    autoUpdateDownloading = "正在下载 APK..."
    autoUpdateInstall = "安装"

    // Settings - Device guides
    guideSection = "使用指南"
    guideSectionDesc = "USB 调试 / Root / 无障碍 快速上手"
    guideUsb = "USB 调试"
    guideUsbDesc = "开发者模式、ADB 连接与 APK 交付"
    guideRoot = "Root 权限"
    guideRootDesc = "root-plugin 使用、风险与审计"
    guideAccessibility = "无障碍"
    guideAccessibilityDesc = "屏幕级自动化能力说明与开启方式"
    guideClose = "关闭"

    // Settings - Agent
    agentAddHumanTouch = "添加真人感"
    agentAddScheduled = "添加定时"
    agentApiReturnedModels = "API 返回模型"
    agentFromGlobalPool = "从全局工具池安装"
    agentFromSkillPool = "从全局技能池安装"
    agentInstallHelp = "三种安装方式：①从全局工具池安装 ②Agent 自行搜索下载安装 ③用户手动下载并提供路径，Agent 自行安装"
    agentLastFired = "上次触发: %s"
    agentLoopMode = "Loop 模式"
    agentLoopModeDesc = "Agent 会根据任务复杂度自动选择合适的执行模式，无需手动切换。"
    agentNoProvider = "尚未添加 API 供应商，请先前往「框架设置」配置"
    agentNoSkills = "该智能体尚未拉取本地技能，可从全局技能池 skill.pull 拉取，或 skill.create 创建。"
    agentNoTriggers = "暂无触发器。添加定时任务让 Agent 在指定时间自动执行。"
    agentParams = "Agent 参数"
    agentPlugins = "Agent 插件"
    agentProviderModel = "供应商 & 模型"
    agentRefreshFileList = "刷新文件列表"
    agentRefreshModels = "刷新模型列表"
    agentRemainingCount = "... 还有 %d 个"
    agentSelectModel = "选择模型"
    agentShellTimeout = "Shell 命令超时"
    agentShellTimeoutDesc = "单个命令最长执行时间（秒）"
    agentSkills = "智能体技能(Agent Skills)"
    agentSkillPool = "全局技能池"
    agentTools = "智能体工具(Agent Tools)"
    agentTriggerHuman = "真人"
    agentTriggers = "定时任务 & 触发器"
    agentTriggerScheduled = "定时"
    agentWorkspaceFiles = "工作区文件"

    // Agent 引导进度 (P2-13)
    agentBoostPanel = "引导进度"
    agentBoostPanelDesc = "Agent 初始化引导四项 — 身份 / 头像 / 主题 / 灵魂"
    agentBoostDone = "已完成初始化"
    agentBoostProgress = "已完成 %1\$d/4 · 未完成：%2\$s"
    agentBoostItemIdentity = "身份"
    agentBoostItemAvatar = "头像"
    agentBoostItemTheme = "主题"
    agentBoostItemSoul = "灵魂"
    agentBoostHint = "引导文档 boost.md 仍在工作区 — 确认引导完成后可在「工作区文件」中删除"

    // Settings - Framework
    frameworkAddProvider = "新增API供应商"
    frameworkApiProvider = "API供应商"
    frameworkCollapseList = "收起API供应商列表"
    frameworkContextStrategy = "上下文策略"
    frameworkContextStrategyDesc = "内置 · Reasonix 四级折叠"
    frameworkEditConnection = "编辑连接"
    frameworkGlobalPlugins = "全局插件"
    frameworkGlobalSkills = "全局技能(Skills)"
    frameworkGlobalTools = "全局工具(Tools)"
    frameworkMemoryBackend = "记忆管理后端"
    frameworkMemoryBackendDesc = "内置 · Markdown 文件"
    frameworkMemoryManagement = "记忆管理"
    frameworkNewConnection = "新增连接"
    frameworkPluginManagement = "插件管理"
    frameworkPluginManagementDesc = "浏览、安装、管理 Agent 插件"
    frameworkProviderLabel = "供应商"
    frameworkSaveConnection = "保存"
    frameworkTestConnection = "测试"
    frameworkTestingConnection = "正在测试连接..."

    // Settings - Sidebar tabs
    sidebarSettingsAgent = "智能体设置"
    sidebarSettingsFramework = "框架设置"
    sidebarSettingsSystem = "系统设置"

    // Security
    securityAgentDocs = "Agent 文档"
    securityFingerprint = "指纹: %s"
    securityFileIntegrity = "文件完整性防护"
    securityFileIntegrityDesc = "已启用 — 保护核心目录不被修改"
    securityKernelDir = "内核目录"
    securityKernelIntegrity = "内核完整性防护"
    securityKernelIntegrityDesc = "已启用 — 阻止 Agent 执行危险命令"
    securityKeyStore = "密钥存储"
    securityNoTrusted = "暂无受信任的框架设备。通过 ACP 配对添加。"
    securityPluginCache = "插件缓存"
    securityPluginIntegrity = "插件完整性防护"
    securityPluginIntegrityDesc = "已启用 — 验证插件签名和版本兼容性"
    securityProtectedDirs = "受保护的目录："
    securityRules = "安全规则"
    securityTrusted = "已信任"
    securityTrustedCount = "已信任 %d 个框架设备"
    securityTrustedFramework = "框架信任列表"

    pluginMarketTitle = "插件管理"
    forceRefresh = "强制刷新"
    marketTab = "市场"
    installedTab = "已安装"
    noPluginsAvailable = "暂无可用插件"
    noInstalledPlugins = "暂无已安装插件"
    refreshHint = "点击刷新获取插件列表"
    availablePrefix = "可用: "
    installedPrefix = "已安装: "
    activePrefix = "活跃: "
    builtinBadge = "内置"
    embeddedBadge = "已嵌入"
    activeBadge = "活跃"
    disabledBadge = "已禁用"
    notPublishedBadge = "暂未发布"
    uninstall = "卸载"
    install = "安装"
    verifying = "校验中..."
    installedBadge = "已安装"
    activatedBadge = "已激活"
    failedBadge = "失败"
    retry = "重试"
    pluginNotFound = "插件未找到: "
    notInstalledBadge = "未安装"
    typePrefix = "类型: "
    commandsLabel = "命令列表"
    permissionsLabel = "权限"
    enable = "启用"
    disable = "禁用"
    installPlugin = "安装插件"
    errorPrefix = "错误: "
    cronTitle = "CRON 定时任务"
    cronExpression = "Cron 表达式"
    cronPlaceholder = "分 时 日 月 周  例: 0 9 * * *"
    cronHint = "时间参数让 Agent 帮你算，例如：帮我每天早上9点生成昨日摘要"
    actionLabel = "执行动作"
    actionPlaceholder = "描述 Agent 需要执行的任务..."
    cronTip = "在聊天框告诉 Agent：帮我在每天早上9点生成昨日摘要 — Agent 会自动调用 self.trigger add 配置"
    add = "添加"
    scheduleTitle = "伪人模式"
    scheduleParams = "配置参数"
    scheduleParamsPlaceholder = "窗口,count=N,interval=M"
    scheduleFormatHint = "格式: HH:MM-HH:MM,count=N,interval=M  例: 08:00-22:00,count=3,interval=60"
    scheduleTip = "在聊天框告诉 Agent：帮我在每天上午10点到下午6点之间找我聊4次天，间隔至少1小时 — Agent 会自动调用 self.trigger add schedule 配置"
    noEntries = "暂无条目"
    noDocs = "暂无文档"
    agentToolsDesc = "该 Agent 专属的命令工具，仅在当前 Agent 可用。全局命令通过 self.tools 查看。"
    noToolsConfigured = "暂未配置专属工具。Agent 使用全局工具池（self.tools）中的命令。"
    agentSkillsDesc = "该 Agent 本地已加载的技能，Markdown 剧本格式。使用 skill.run <name> 执行。"
    noWorkspaceDocs = "工作区暂无文档"
    deleteDoc = "删除文档"
    deleteConfirm = "确定删除此文档？此操作不可恢复。"
    agentToolDeleteConfirm = "确定删除命令集 %s ？此操作将移除该命令集及其全部命令，不可恢复。"
    resetDoc = "重置文档"
    resetConfirm = "确定将此文档重置为预置版？当前修改将丢失。"
    openDoc = "打开"
    editOpenFailed = "没有可打开此文档的应用。"
    optimizedBadge = "已优化"
    apiReturned = "API 返回"
    builtinCategory = "内置"
    officialCategory = "官方"
    customCategory = "自建"
    lightTheme = "亮色"
    systemTheme = "跟随系统"
    notifPersistent = "通知栏常驻"
    silentRunning = "静默运行"
    foregroundOnly = "仅前台使用"
    notifPersistentDesc = "状态栏显示图标，保活最强，推荐"
    silentRunningDesc = "隐藏通知图标，前台服务仍在后台"
    foregroundOnlyDesc = "退出时释放服务，最省电"
    rolePlanner = "规划器 (拆解)"
    roleWorker = "执行器 (worker)"
    roleVerifier = "验收器 (verifier)"
    roleSynthesizer = "合成器 (synthesizer)"
    roleWorkerAlt = "备用执行器 (worker.alt)"

    // 侧边栏 — Framework Status 三状态（标签 + 解释）
    frameworkStatusOnline = "在线"
    frameworkStatusOnlineDesc = "Chat 开放 · 接受委派任务"
    frameworkStatusBusy = "忙碌"
    frameworkStatusBusyDesc = "Chat 开放 · 委派任务排队等待"
    frameworkStatusOffline = "离线"
    frameworkStatusOfflineDesc = "Chat 关闭 · 不响应任何外部请求"

    // 卡片对话框共用
    close = "关闭"
    cardEdit = "编辑"
    cardSave = "保存"

    // 框架名片对话框
    frameworkCardTitle = "框架名片"
    frameworkCardRemarkLabel = "备注名称"
    frameworkCardVersion = "版本: %s"
    frameworkCardUntrusted = "未信任"
    frameworkCardHostedAgents = "托管智能体 (%d)"
    frameworkCardDelete = "删除框架"
    frameworkCardTrust = "信任框架"
    frameworkCardUntwin = "解除孪生"
    frameworkCardUntrust = "解除信任"

    // 智能体名片对话框
    agentCardTitle = "智能体名片"
    agentCardNameLabel = "智能体名称"
    agentCardIntroLabel = "智能体简介"
    agentCardIntroField = "简介"
    agentCardNoIntro = "暂无简介"
    agentCardWorkspaceFiles = "工作区文件 (%d)"
    agentCardDelete = "删除智能体"
    agentCardDeleteTitle = "确认删除"
    agentCardDeleteBody = "确定要永久删除「%s」吗？该操作将删除智能体的所有数据，包括工作区文件、记忆和会话记录。"
    agentCardSwitch = "切换到此智能体"

    // 新建智能体对话框
    newAgentTitle = "新建智能体"
    newAgentNameLabel = "智能体名称 *"
    newAgentNamePlaceholder = "例如：研究助手"
    newAgentFolderLabel = "工作区文件夹名称"
    newAgentFolderPlaceholder = "默认与智能体名称相同"
    newAgentFolderHint = "将创建于: %s"
    newAgentIntroLabel = "智能体简介"
    newAgentIntroPlaceholder = "描述这个智能体的职责和能力..."
    newAgentCreate = "创建智能体"
    newAgentDefaultName = "智能体 %d"

    // 添加框架对话框
    addFrameworkTitle = "添加框架"
    addFrameworkType = "框架类型"
    addFrameworkName = "框架名称"
    addFrameworkNamePlaceholder = "如: 办公室电脑"
    addFrameworkAddress = "地址 (可选)"
    addFrameworkAddrPortPlaceholder = "如: 192.168.1.100:%d"
    addFrameworkAddrGenericPlaceholder = "如: localhost:8080 或 /path/to/socket"
    addFrameworkScanLan = "扫描局域网"
    addFrameworkDiscovered = "发现的设备:"
    pairPendingRequests = "待处理配对请求"
    pairNoPending = "暂无配对请求"
    pairAccept = "同意"
    pairDecline = "拒绝"
    pairAccepted = "已同意 — 双方已加入通讯录"
    pairDeclined = "已拒绝"
    pairRespondFailed = "回复失败，请确认对方在线"
    pairScanEmpty = "未发现局域网框架"
    pairScanHint = "点击「扫描局域网」刷新列表；MengPaw 设备显示「添加」按钮发送配对请求"
    pairRequestSent = "配对请求已发送，等待对方同意"
    pairRequestFailed = "发送失败 — 请确认对方在线、两台设备在同一 WiFi（防火墙可能拦截）"
    pairClearProcessed = "清除已处理"
    pairManualAdd = "手动添加"
    pairAddedLocal = "已添加（非 MengPaw 框架直接入册）"
    frameworkPairRequestTitle = "框架配对请求"
    pairRequestBody = "%s 请求加入你的框架通讯录"
    pairRequestHint = "同意后双方加入通讯录。建议先与对方核对指纹短码，确认是本人的设备。"
    pairRequestLater = "稍后"
    pairHistory = "已处理请求"
    pairHistoryEmpty = "暂无已处理请求"
    bubbleCopy = "复制"
    bubbleBigBang = "大爆炸"
    bubbleQuote = "引用"
    bubbleSaveImages = "保存图片"
    bubbleMarkImage = "标注图片"
    bubbleShare = "分享"
    bubbleRetract = "撤回"
    bubbleShareTo = "分享到"
    outputDirTitle = "输出目录"
    outputDirCurrent = "当前输出目录"
    outputDirUnwritable = "⚠️ 不可写 — 点击授权『所有文件访问』，Agent 交付的文件才会出现在这里"
    outputDirGrant = "去授权"
    outputPermissionTitle = "需要『所有文件访问』权限"
    outputPermissionBody = "MengPaw 会把交付的文件写入公共输出目录 /storage/emulated/0/MengPaw/，手机文件管理器可直接查看。"
    outputPermissionGrant = "去授权"
    outputPermissionLater = "暂不"
    permissionLevelTitle = "安全分级权限"
    permissionStandard = "标准"
    permissionTrusted = "信任"
    permissionStandardDesc = "标准 — 中危操作需提升权限（点击切换为信任）"
    permissionTrustedDesc = "信任 — 中危操作也放行（点击切换为标准）"
    permissionLow = "• 普通（新建/写入文件、通知等）— 始终放行"
    permissionMidStandard = "• 中危（删除/修改文件、剪贴板、截图录屏）— 标准拒绝"
    permissionMidTrusted = "• 中危（删除/修改文件、剪贴板、截图录屏）— 信任放行"
    permissionHigh = "• 高危（清空/卸载/系统级/拍照）— 每次弹窗询问，拒绝即阻挡"
    frameworkIdentityLabel = "本机指纹码"
    frameworkIdentityDefaultPlaceholder = "缺省 = 显示指纹码"
    frameworkUnknown = "未知"

    // 记忆孪生配对弹窗
    twinRequestTitle = "记忆孪生配对请求"
    twinRequestWarning = "请确认是个人设备请求，请勿与他人设备记忆孪生"
    twinRequestDevice = "请求设备: %s"
    twinRequestModel = "型号: %s"
    twinRequestAgreeDesc = "同意后，双方 Agent 的记忆将开始同步。"
    twinRequestAgree = "同意"
    twinRequestDisagree = "不同意"
    twinVerifyTitle = "验证配对码"
    twinVerifyDesc = "请确认两台设备显示相同的 6 位验证码"
    twinVerifyPeer = "配对设备: %s..."
    twinVerifyWarning = "如验证码不一致，说明存在中间人攻击，请立即取消"
    twinVerifyConfirm = "一致，确认配对"
    twinConfirmTitle = "记忆孪生配对"
    twinConfirmIntro = "即将与以下设备建立记忆孪生配对："
    twinConfirmWarning = "配对后本设备的 Agent 记忆将与对方同步。请确认是个人设备，勿与他人设备配对。"
    twinConfirmAction = "确认配对"
    twinPairedToast = "记忆孪生配对成功！执行 twin.sync 立即同步工作区"
    unknown = "未知"

    // 工作区文件 — memory 聚合条目合成文案
    workspaceMemoryFolder = "memory"
    workspaceMemoryHeader = "## memory — 记忆目录（三重记忆）"
    workspaceMemorySummary = "长期 %d · 中期 %d · 项目 %d · 共 %d 个文档"
    workspaceNotesFolder = "Notes"
    workspaceNotesSummary = "共 %d 个文档"
    workspaceEvolutionFolder = "evolution"
    workspaceEvolutionSummary = "失败模式 %d · 用户反应 %d · 框架反馈 %d · 共 %d 个文件"
    workspaceEmptyDoc = "（空文档）"

    // 全局技能池面板 — 来源标签/指定按钮
    skillSourceCore = "核心"
    skillSourcePlugin = "插件"
    skillPin = "指定"

    // 顶栏 — 会话模型标签
    agentNoModel = "智能体还未配置模型"
    agentUnconfigured = "未配置"
    providerVolcano = "火山引擎"
    newSession = "新建会话"
    history = "历史"

}
