// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial

package com.mengpaw.shell.ui.localization

/**
 * English strings (default).
 */
val EnglishStrings = AppStrings().apply {

    isChinese = false
    appName = "MengPaw"
    settings = "Settings"
    back = "Back"

    systemBanner = "Agent is ready. Describe the task you want to accomplish."
    inputPlaceholder = "Describe a task for the Agent..."
    commandOutputLabel = "Command output"
    commandFailedLabel = "Command failed"
    thinking = "Thinking..."
    agentLabel = "Agent"
    stop = "Stop"
    send = "Send"
    voiceInput = "Voice input"
    voiceReleaseToSend = "Release to send"
    voiceSlideToCancel = "Slide up to cancel"
    voiceTooShort = "Too short to send"
    voicePermissionDenied = "Microphone permission is required for voice input"

    llmProvider = "LLM Provider"
    apiEndpoint = "API Endpoint"
    apiKey = "API Key"
    apiKeyShow = "Show"
    apiKeyHide = "Hide"
    model = "Model"

    agent = "Agent"
    maxSteps = "Max Steps"
    maxStepsDesc = "Maximum ReAct iterations before forced stop"
    llmConcurrency = "LLM Concurrency"
    llmConcurrencyDesc = "Max simultaneous LLM API calls (1-50)"
    agentAutoTranslate = "Auto-translate (English models)"
    agentAutoTranslateDesc = "Translate Chinese to English for OpenAI/Grok/Claude models, then back. Off by default — only enabled when you turn it on"

    appearance = "Appearance"
    darkTheme = "Dark Theme"
    darkThemeDesc = "Light / Dark / Follow System"
    language = "Language"
    languageDesc = "Switch UI language"
    languageZh = "中文"
    languageEn = "English"

    agentLanguage = "Agent Language"
    agentLanguageDesc = "Language for Agent's thinking and responses"
    agentLanguageFollowUi = "Follow UI"
    agentLanguageChinese = "中文"
    agentLanguageEnglish = "English"

    expandFileSection = "File Upload"
    expandModeSection = "Execution Mode"
    expandPluginSection = "Plugin Tools"
    filePickImage = "Image"
    filePickDocument = "Document"
    filePickFile = "File"
    filePickCamera = "Camera"
    dragHint = "Long-press to reorder"

    tagModeResearch = "/Research"
    tagModeSilent = "/Silent"
    tagDismiss = "Remove"
    mentionHint = "@mention an agent..."

    // v0.34.4: Swarm is the evolved Mission — subtask decomposition is now handled by Swarm
    placeholderSwarm = "Describe a task for parallel swarm workers with mixed models..."
    placeholderFleet = "Describe a task for Agent fleet collaboration across devices/frameworks..."
    placeholderResearch = "Enter a topic for deep research with source verification..."
    placeholderSilent = "Describe a background task to run silently..."

    about = "About"
    version = "Version"
    core = "Core"
    design = "Design"
    resetDefaults = "Reset to Defaults"

    // Sidebar
    sidebarAgents = "Agents"
    sidebarCurrent = "Current"
    sidebarFeatures = "Features"
    sidebarFrameworkDirectory = "Framework Directory"
    sidebarFrameworkStatus = "Framework Status"
    sidebarNoFriends = "Your agents have no friends yet"
    sidebarPlugins = "Plugins"
    sidebarSettings = "Settings"

    // General
    cancel = "Cancel"
    delete = "Delete"

    // Settings - System
    systemAttribution = "Open Source Attribution"
    systemAttributionDesc = "Code references, inspiration sources, and license compliance"
    systemBackground = "Background Running"
    systemBackgroundMode = "Background Mode"
    systemBackgroundPowerSaver = "Power Saver Mode"
    systemBackgroundPowerSaverDesc = "Reduce background poll frequency and animation frame rate to extend battery life"
    systemBatteryIgnored = "Battery optimization ignored"
    systemBatteryIgnoredDesc = "System will not restrict background running when screen is off"
    systemBatteryNotIgnored = "Battery optimization not ignored"
    systemBatteryNotIgnoredDesc = "Tap to jump to system settings, disable to prevent screen-off restrictions"
    systemCacheSaved = "Cache Saved"
    systemContactUs = "Contact Us"
    systemCopyright = "Copyright"
    systemCopyrightDesc = "© 2026 ShenZhen wowblue culture and technology CO.,LTD."
    systemDaily = "Daily"
    systemEstimatedSavings = "Est. Savings"
    systemGoToBatterySettings = "Go to Settings →"
    systemLegalContact = "Legal & Contact"
    systemLicense = "License"
    systemMonthly = "Monthly"
    systemNoTokenData = "No token usage data yet. Recording starts automatically."
    systemTimezone = "Timezone"
    systemTimezoneAuto = "Auto"
    systemTimezoneShanghai = "Shanghai"
    systemTokenStats = "Token Usage Statistics"
    systemTotalUsage = "Total Usage"
    systemWeekly = "Weekly"

    // Settings - Device guides
    guideSection = "Guides"
    guideSectionDesc = "Quick start: USB debugging / Root / Accessibility"
    guideUsb = "USB Debugging"
    guideUsbDesc = "Developer mode, ADB connection, APK delivery"
    guideRoot = "Root Access"
    guideRootDesc = "root-plugin usage, risks, and audit"
    guideAccessibility = "Accessibility"
    guideAccessibilityDesc = "Screen-level automation: concept and enabling"
    guideClose = "Close"

    // Settings - Agent
    agentAddHumanTouch = "Add Human Touch"
    agentAddScheduled = "Add Scheduled"
    agentApiReturnedModels = "API Returned Models"
    agentFromGlobalPool = "Install from Global Tool Pool"
    agentFromSkillPool = "Install from Global Skill Pool"
    agentInstallHelp = "Three methods: ① Install from global pool ② Agent auto-discovers and installs ③ Manual download with path, Agent installs"
    agentLastFired = "Last fired: %s"
    agentLoopMode = "Loop Mode"
    agentLoopModeDesc = "Agent automatically selects the appropriate execution mode based on task complexity."
    agentNoProvider = "No API provider added yet. Please go to Framework Settings to configure."
    agentNoSkills = "No local skills yet. Use skill.pull to fetch from the global pool, or skill.create to author one."
    agentNoTriggers = "No triggers yet. Add scheduled tasks for Agent to execute automatically."
    agentParams = "Agent Parameters"
    agentPlugins = "Agent Plugins"
    agentProviderModel = "Provider & Model"
    agentRefreshFileList = "Refresh file list"
    agentRefreshModels = "Refresh Model List"
    agentRemainingCount = "... and %d more"
    agentSelectModel = "Select Model"
    agentShellTimeout = "Shell Command Timeout"
    agentShellTimeoutDesc = "Max execution time per command (seconds)"
    agentSkills = "Agent Skills"
    agentSkillPool = "Global Skill Pool"
    agentTools = "Agent Tools"
    agentTriggerHuman = "Human"
    agentTriggers = "Scheduled Tasks & Triggers"
    agentTriggerScheduled = "Scheduled"
    agentWorkspaceFiles = "Workspace Files"

    // Agent Onboarding Progress (P2-13)
    agentBoostPanel = "Onboarding Progress"
    agentBoostPanelDesc = "Agent initialization checklist — identity / avatar / theme / soul"
    agentBoostDone = "Onboarding complete"
    agentBoostProgress = "Completed %1\$d/4 · Missing: %2\$s"
    agentBoostItemIdentity = "Identity"
    agentBoostItemAvatar = "Avatar"
    agentBoostItemTheme = "Theme"
    agentBoostItemSoul = "Soul"
    agentBoostHint = "boost.md is still in the workspace — delete it in Workspace Files once onboarding is done"

    // Settings - Framework
    frameworkAddProvider = "Add API Provider"
    frameworkApiProvider = "API Provider"
    frameworkCollapseList = "Collapse Provider List"
    frameworkContextStrategy = "Context Strategy"
    frameworkContextStrategyDesc = "Built-in · Reasonix 4-Level Fold"
    frameworkEditConnection = "Edit Connection"
    frameworkGlobalPlugins = "Global Plugins"
    frameworkGlobalSkills = "Global Skills"
    frameworkGlobalTools = "Global Tools"
    frameworkMemoryBackend = "Memory Backend"
    frameworkMemoryBackendDesc = "Built-in · Markdown files"
    frameworkMemoryManagement = "Memory Management"
    frameworkNewConnection = "New Connection"
    frameworkPluginManagement = "Plugin Management"
    frameworkPluginManagementDesc = "Browse, install, manage Agent plugins"
    frameworkProviderLabel = "Provider"
    frameworkSaveConnection = "Save"
    frameworkTestConnection = "Test"
    frameworkTestingConnection = "Testing connection..."

    // Settings - Sidebar tabs
    sidebarSettingsAgent = "Agent Settings"
    sidebarSettingsFramework = "Framework Settings"
    sidebarSettingsSystem = "System Settings"

    // Security
    securityAgentDocs = "Agent Documents"
    securityFingerprint = "Fingerprint: %s"
    securityFileIntegrity = "File Integrity Protection"
    securityFileIntegrityDesc = "Enabled — Protects core directories from modification"
    securityKernelDir = "Kernel Directory"
    securityKernelIntegrity = "Kernel Integrity Protection"
    securityKernelIntegrityDesc = "Enabled — Prevents Agent from executing dangerous commands"
    securityKeyStore = "Key Store"
    securityNoTrusted = "No trusted framework devices yet. Add via ACP pairing."
    securityPluginCache = "Plugin Cache"
    securityPluginIntegrity = "Plugin Integrity Protection"
    securityPluginIntegrityDesc = "Enabled — Verifies plugin signatures and version compatibility"
    securityProtectedDirs = "Protected Directories:"
    securityRules = "Security Rules"
    securityTrusted = "Trusted"
    securityTrustedCount = "Trusted %d framework devices"
    securityTrustedFramework = "Framework Trust List"

    pluginMarketTitle = "Plugin Management"
    forceRefresh = "Force Refresh"
    marketTab = "Market"
    installedTab = "Installed"
    noPluginsAvailable = "No plugins available"
    noInstalledPlugins = "No installed plugins"
    refreshHint = "Tap refresh to load the plugin list"
    availablePrefix = "Available: "
    installedPrefix = "Installed: "
    activePrefix = "Active: "
    builtinBadge = "Built-in"
    embeddedBadge = "Embedded"
    activeBadge = "Active"
    disabledBadge = "Disabled"
    notPublishedBadge = "Not Published"
    uninstall = "Uninstall"
    install = "Install"
    verifying = "Verifying..."
    installedBadge = "Installed"
    activatedBadge = "Activated"
    failedBadge = "Failed"
    retry = "Retry"
    pluginNotFound = "Plugin not found: "
    notInstalledBadge = "Not Installed"
    typePrefix = "Type: "
    commandsLabel = "Commands"
    permissionsLabel = "Permissions"
    enable = "Enable"
    disable = "Disable"
    installPlugin = "Install Plugin"
    errorPrefix = "Error: "
    cronTitle = "CRON Scheduled Task"
    cronExpression = "Cron Expression"
    cronPlaceholder = "min hour dom mon dow  e.g. 0 9 * * *"
    cronHint = "Let the Agent compute the schedule, e.g. \"generate yesterday's digest every 9am\""
    actionLabel = "Action"
    actionPlaceholder = "Describe the task for the Agent..."
    cronTip = "Tell the Agent in chat: \"generate yesterday's digest every 9am\" — it will call self.trigger add"
    add = "Add"
    scheduleTitle = "Truman Show"
    scheduleParams = "Parameters"
    scheduleParamsPlaceholder = "window,count=N,interval=M"
    scheduleFormatHint = "Format: HH:MM-HH:MM,count=N,interval=M  e.g. 08:00-22:00,count=3,interval=60"
    scheduleTip = "Tell the Agent in chat: \"chat with me 4 times between 10am-6pm daily, ≥1h apart\" — it will call self.trigger add schedule"
    noEntries = "No entries"
    noDocs = "No docs"
    agentToolsDesc = "Agent-specific command tools, only available to this agent. Global commands via self.tools."
    noToolsConfigured = "No agent-specific tools configured. Uses the global tool pool (self.tools)."
    agentSkillsDesc = "Skills loaded for this agent (Markdown scripts). Run via skill.run <name>."
    noWorkspaceDocs = "No workspace documents"
    deleteDoc = "Delete Document"
    deleteConfirm = "Delete this document? This cannot be undone."
    agentToolDeleteConfirm = "Delete command set %s? This removes the set and all its commands. Cannot be undone."
    resetDoc = "Reset Document"
    resetConfirm = "Reset this document to the built-in version? Current changes will be lost."
    openDoc = "Open"
    editOpenFailed = "No app can open this document."
    optimizedBadge = "Optimized"
    apiReturned = "From API"
    builtinCategory = "Built-in"
    officialCategory = "Official"
    customCategory = "Custom"
    lightTheme = "Light"
    systemTheme = "System"
    notifPersistent = "Persistent Notification"
    silentRunning = "Silent Running"
    foregroundOnly = "Foreground Only"
    notifPersistentDesc = "Status bar icon, strongest keep-alive (recommended)"
    silentRunningDesc = "Hidden notification icon, foreground service still active"
    foregroundOnlyDesc = "Service released on exit, most battery-efficient"
    rolePlanner = "Planner"
    roleWorker = "Worker"
    roleVerifier = "Verifier"
    roleSynthesizer = "Synthesizer"
    roleWorkerAlt = "Alternate Worker"

    // Sidebar — Framework Status (labels + explanations)
    frameworkStatusOnline = "Online"
    frameworkStatusOnlineDesc = "Chat open · Accepting delegated tasks"
    frameworkStatusBusy = "Busy"
    frameworkStatusBusyDesc = "Chat open · Delegated tasks queued"
    frameworkStatusOffline = "Offline"
    frameworkStatusOfflineDesc = "Chat closed · Not responding to external requests"

    // Card dialogs — shared
    close = "Close"
    cardEdit = "Edit"
    cardSave = "Save"

    // Framework card dialog
    frameworkCardTitle = "Framework Card"
    frameworkCardRemarkLabel = "Remark Name"
    frameworkCardVersion = "Version: %s"
    frameworkCardUntrusted = "Untrusted"
    frameworkCardHostedAgents = "Hosted Agents (%d)"
    frameworkCardDelete = "Delete Framework"
    frameworkCardTrust = "Trust framework"
    frameworkCardUntwin = "Untwin"
    frameworkCardUntrust = "Untrust"

    // Agent card dialog
    agentCardTitle = "Agent Card"
    agentCardNameLabel = "Agent Name"
    agentCardIntroLabel = "Agent Intro"
    agentCardIntroField = "Intro"
    agentCardNoIntro = "No intro yet"
    agentCardWorkspaceFiles = "Workspace Files (%d)"
    agentCardDelete = "Delete Agent"
    agentCardDeleteTitle = "Confirm Delete"
    agentCardDeleteBody = "Delete \"%s\" permanently? This removes all agent data, including workspace files, memory, and session records."
    agentCardSwitch = "Switch to this Agent"

    // New agent dialog
    newAgentTitle = "New Agent"
    newAgentNameLabel = "Agent Name *"
    newAgentNamePlaceholder = "e.g. Research Assistant"
    newAgentFolderLabel = "Workspace Folder Name"
    newAgentFolderPlaceholder = "Defaults to agent name"
    newAgentFolderHint = "Will be created at: %s"
    newAgentIntroLabel = "Agent Intro"
    newAgentIntroPlaceholder = "Describe this agent's role and capabilities..."
    newAgentCreate = "Create Agent"
    newAgentDefaultName = "Agent %d"

    // Add framework dialog
    addFrameworkTitle = "Add Framework"
    addFrameworkType = "Framework Type"
    addFrameworkName = "Framework Name"
    addFrameworkNamePlaceholder = "e.g. Office PC"
    addFrameworkAddress = "Address (optional)"
    addFrameworkAddrPortPlaceholder = "e.g. 192.168.1.100:%d"
    addFrameworkAddrGenericPlaceholder = "e.g. localhost:8080 or /path/to/socket"
    addFrameworkScanLan = "Scan LAN"
    addFrameworkDiscovered = "Discovered devices:"
    pairPendingRequests = "Pending pair requests"
    pairNoPending = "No pending pair requests"
    pairAccept = "Accept"
    pairDecline = "Decline"
    pairAccepted = "Accepted — both added to directory"
    pairDeclined = "Declined"
    pairRespondFailed = "Failed to respond — check peer online"
    pairScanEmpty = "No frameworks found on LAN"
    pairScanHint = "Tap Scan LAN to refresh; MengPaw devices show Add to send a pair request"
    pairRequestSent = "Pair request sent — waiting for approval"
    pairRequestFailed = "Send failed — check peer online, same WiFi (firewall may block)"
    pairClearProcessed = "Clear processed"
    pairManualAdd = "Manual Add"
    pairAddedLocal = "Added (non-MengPaw added directly)"
    frameworkPairRequestTitle = "Framework Pair Request"
    pairRequestBody = "%s requests to join your framework directory"
    pairRequestHint = "Accepting adds both sides to the directory. Verify the fingerprint short code matches your own device first."
    pairRequestLater = "Later"
    pairHistory = "Processed Requests"
    pairHistoryEmpty = "No processed requests yet"
    bubbleCopy = "Copy"
    bubbleBigBang = "BigBang"
    bubbleQuote = "Quote"
    bubbleSaveImages = "Save images"
    bubbleMarkImage = "Mark image"
    bubbleShare = "Share"
    bubbleRetract = "Retract"
    bubbleShareTo = "Share to"
    outputDirTitle = "Output Directory"
    outputDirCurrent = "Current output directory"
    outputDirUnwritable = "⚠️ Not writable — grant 'All files access' so Agent deliveries appear here"
    outputDirGrant = "Grant"
    outputPermissionTitle = "All files access required"
    outputPermissionBody = "MengPaw writes deliverables to /storage/emulated/0/MengPaw/, visible in the file manager."
    outputPermissionGrant = "Grant"
    outputPermissionLater = "Later"
    permissionLevelTitle = "Safety levels"
    permissionStandard = "Standard"
    permissionTrusted = "Trusted"
    permissionStandardDesc = "Standard — mid-risk actions need elevated permission (tap to switch to Trusted)"
    permissionTrustedDesc = "Trusted — mid-risk actions allowed (tap to switch to Standard)"
    permissionLow = "• Low (create/write files, notifications) — always allowed"
    permissionMidStandard = "• Mid (delete/modify files, clipboard, screenshots) — denied on Standard"
    permissionMidTrusted = "• Mid (delete/modify files, clipboard, screenshots) — allowed on Trusted"
    permissionHigh = "• High (wipe/uninstall/system/photo) — asks every time, denial blocks"
    frameworkIdentityLabel = "Local fingerprint"
    frameworkIdentityDefaultPlaceholder = "Default = show fingerprint"
    frameworkUnknown = "Unknown"

    // Memory twin pairing dialogs
    twinRequestTitle = "Memory Twin Pairing Request"
    twinRequestWarning = "Confirm this is your own device. Do NOT pair memory twins with others."
    twinRequestDevice = "Requesting device: %s"
    twinRequestModel = "Model: %s"
    twinRequestAgreeDesc = "After consent, both agents' memories will begin syncing."
    twinRequestAgree = "Agree"
    twinRequestDisagree = "Disagree"
    twinVerifyTitle = "Verify Pairing Code"
    twinVerifyDesc = "Confirm both devices show the same 6-digit code"
    twinVerifyPeer = "Pairing device: %s..."
    twinVerifyWarning = "If the codes differ, a man-in-the-middle attack may be present. Cancel immediately."
    twinVerifyConfirm = "Match — Confirm Pairing"
    twinConfirmTitle = "Memory Twin Pairing"
    twinConfirmIntro = "A memory twin pairing will be established with:"
    twinConfirmWarning = "After pairing, this device's agent memory will sync with the peer. Confirm this is your own device; do not pair with others."
    twinConfirmAction = "Confirm Pairing"
    twinPairedToast = "Memory twin paired! Run twin.sync to sync the workspace now"
    unknown = "Unknown"

    // Workspace files — memory folder synthesized labels
    workspaceMemoryFolder = "memory"
    workspaceMemoryHeader = "## memory — Memory folder (triple-track)"
    workspaceMemorySummary = "Long-term %d · Mid-term %d · Project %d · %d docs"
    workspaceNotesFolder = "Notes"
    workspaceNotesSummary = "%d note(s)"
    workspaceEvolutionFolder = "evolution"
    workspaceEvolutionSummary = "Failures %d · Reactions %d · Feedback %d · %d files"
    workspaceEmptyDoc = "(empty)"

    // Global skill pool panel — source badge / pin button
    skillSourceCore = "Core"
    skillSourcePlugin = "Plugin"
    skillPin = "Pin"

    // Top bar — session model label
    agentNoModel = "Agent model not configured"
    agentUnconfigured = "Not configured"
    providerVolcano = "Volcano Engine"
    newSession = "New session"
    history = "History"

}
