// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial

package com.mengpaw.shell.ui.localization

/**
 * Localized strings for the MengPaw UI.
 * Switch between Chinese (zh) and English (en) with one click.
 */
data class AppStrings(
    // App
    val isChinese: Boolean,
    val appName: String,
    val settings: String,
    val back: String,

    // Main Screen
    val systemBanner: String,
    val inputPlaceholder: String,
    val commandOutputLabel: String,
    val commandFailedLabel: String,
    val roleRoutingTitle: String,
    val thinking: String,
    val agentLabel: String,
    val stop: String,
    val send: String,

    // Settings - LLM Provider
    val llmProvider: String,
    val apiEndpoint: String,
    val apiKey: String,
    val apiKeyShow: String,
    val apiKeyHide: String,
    val model: String,

    // Settings - Agent
    val agent: String,
    val maxSteps: String,
    val maxStepsDesc: String,
    val llmConcurrency: String,
    val llmConcurrencyDesc: String,

    // Settings - Appearance
    val appearance: String,
    val darkTheme: String,
    val darkThemeDesc: String,
    val language: String,
    val languageDesc: String,
    val languageZh: String,
    val languageEn: String,

    // Settings - Agent Language
    val agentLanguage: String,
    val agentLanguageDesc: String,
    val agentLanguageFollowUi: String,
    val agentLanguageChinese: String,
    val agentLanguageEnglish: String,

    // Expand panel
    val expandFileSection: String,
    val expandModeSection: String,
    val expandPluginSection: String,
    val filePickImage: String,
    val filePickDocument: String,
    val filePickFile: String,
    val filePickCamera: String,
    val dragHint: String,

    // Execution mode tags
    val tagModeMission: String,
    val tagModeResearch: String,
    val tagModeTranslate: String,
    val tagModeSilent: String,
    val tagDismiss: String,
    val mentionHint: String,

    // Mode-specific placeholders
    val placeholderMission: String,
    val placeholderResearch: String,
    val placeholderTranslate: String,
    val placeholderSilent: String,

    // Settings - About
    val about: String,
    val version: String,
    val core: String,
    val design: String,
    val resetDefaults: String,

    // Sidebar
    val sidebarAgents: String,
    val sidebarCurrent: String,
    val sidebarFeatures: String,
    val sidebarFrameworkDirectory: String,
    val sidebarFrameworkStatus: String,
    val sidebarNoFriends: String,
    val sidebarPlugins: String,
    val sidebarSettings: String,

    // General
    val cancel: String,
    val delete: String,

    // Settings - System
    val systemAttribution: String,
    val systemAttributionDesc: String,
    val systemBackground: String,
    val systemBackgroundMode: String,
    val systemBackgroundPowerSaver: String,
    val systemBackgroundPowerSaverDesc: String,
    val systemBatteryIgnored: String,
    val systemBatteryIgnoredDesc: String,
    val systemBatteryNotIgnored: String,
    val systemBatteryNotIgnoredDesc: String,
    val systemCacheSaved: String,
    val systemContactUs: String,
    val systemCopyright: String,
    val systemCopyrightDesc: String,
    val systemDaily: String,
    val systemEstimatedSavings: String,
    val systemGoToBatterySettings: String,
    val systemLegalContact: String,
    val systemLicense: String,
    val systemMonthly: String,
    val systemNoTokenData: String,
    val systemTimezone: String,
    val systemTimezoneAuto: String,
    val systemTimezoneShanghai: String,
    val systemTokenStats: String,
    val systemTotalUsage: String,
    val systemWeekly: String,

    // Settings - Agent
    val agentAddHumanTouch: String,
    val agentAddScheduled: String,
    val agentApiReturnedModels: String,
    val agentFromGlobalPool: String,
    val agentFromSkillPool: String,
    val agentInstallHelp: String,
    val agentLastFired: String,
    val agentLoopMode: String,
    val agentLoopModeDesc: String,
    val agentNoProvider: String,
    val agentNoSkills: String,
    val agentNoTriggers: String,
    val agentParams: String,
    val agentPlugins: String,
    val agentProviderModel: String,
    val agentRefreshFileList: String,
    val agentRefreshModels: String,
    val agentRemainingCount: String,
    val agentSelectModel: String,
    val agentShellTimeout: String,
    val agentShellTimeoutDesc: String,
    val agentSkills: String,
    val agentSkillPool: String,
    val agentTools: String,
    val agentTriggerHuman: String,
    val agentTriggers: String,
    val agentTriggerScheduled: String,
    val agentWorkspaceFiles: String,

    // Settings - Framework
    val frameworkAddProvider: String,
    val frameworkApiProvider: String,
    val frameworkCollapseList: String,
    val frameworkContextStrategy: String,
    val frameworkContextStrategyDesc: String,
    val frameworkEditConnection: String,
    val frameworkGlobalPlugins: String,
    val frameworkGlobalSkills: String,
    val frameworkGlobalTools: String,
    val frameworkMemoryBackend: String,
    val frameworkMemoryBackendDesc: String,
    val frameworkMemoryManagement: String,
    val frameworkNewConnection: String,
    val frameworkPluginManagement: String,
    val frameworkPluginManagementDesc: String,
    val frameworkProviderLabel: String,
    val frameworkSaveConnection: String,
    val frameworkTestConnection: String,
    val frameworkTestingConnection: String,

    // Settings - Sidebar tabs
    val sidebarSettingsAgent: String,
    val sidebarSettingsFramework: String,
    val sidebarSettingsSystem: String,

    // Security
    val securityAgentDocs: String,
    val securityFingerprint: String,
    val securityFileIntegrity: String,
    val securityFileIntegrityDesc: String,
    val securityKernelDir: String,
    val securityKernelIntegrity: String,
    val securityKernelIntegrityDesc: String,
    val securityKeyStore: String,
    val securityNoTrusted: String,
    val securityPluginCache: String,
    val securityPluginIntegrity: String,
    val securityPluginIntegrityDesc: String,
    val securityProtectedDirs: String,
    val securityRules: String,
    val securityTrusted: String,
    val securityTrustedCount: String,
    val securityTrustedFramework: String,

    // ── 插件市场 / 详情（英文化补全）──
    val pluginMarketTitle: String,
    val forceRefresh: String,
    val marketTab: String,
    val installedTab: String,
    val noPluginsAvailable: String,
    val noInstalledPlugins: String,
    val refreshHint: String,
    val availablePrefix: String,
    val installedPrefix: String,
    val activePrefix: String,
    val builtinBadge: String,
    val embeddedBadge: String,
    val activeBadge: String,
    val disabledBadge: String,
    val notPublishedBadge: String,
    val uninstall: String,
    val install: String,
    val verifying: String,
    val installedBadge: String,
    val failedBadge: String,
    val retry: String,
    val pluginNotFound: String,
    val notInstalledBadge: String,
    val typePrefix: String,
    val commandsLabel: String,
    val permissionsLabel: String,
    val enable: String,
    val disable: String,
    val installPlugin: String,
    val errorPrefix: String,
    // ── 触发器对话框 ──
    val cronTitle: String,
    val cronExpression: String,
    val cronPlaceholder: String,
    val cronHint: String,
    val actionLabel: String,
    val actionPlaceholder: String,
    val cronTip: String,
    val add: String,
    val scheduleTitle: String,
    val scheduleParams: String,
    val scheduleParamsPlaceholder: String,
    val scheduleFormatHint: String,
    val scheduleTip: String,
    // ── 设置卡片/Agent 设置/框架设置剩余硬编码 ──
    val noEntries: String,
    val noDocs: String,
    val agentToolsDesc: String,
    val noToolsConfigured: String,
    val agentSkillsDesc: String,
    val noWorkspaceDocs: String,
    val deleteDoc: String,
    val deleteConfirm: String,
    val roleRoutingEmpty: String,
    val defaultMainModel: String,
    val optimizedBadge: String,
    val apiReturned: String,
    // ── 枚举 label（中文名兜底用 enLabel 字段; 此处为共用 UI 文案）──
    val builtinCategory: String,
    val officialCategory: String,
    val customCategory: String,
    val lightTheme: String,
    val systemTheme: String,
    val notifPersistent: String,
    val silentRunning: String,
    val foregroundOnly: String,
    val notifPersistentDesc: String,
    val silentRunningDesc: String,
    val foregroundOnlyDesc: String,
    val rolePlanner: String,
    val roleWorker: String,
    val roleVerifier: String,
    val roleSynthesizer: String,
    val roleWorkerAlt: String
)

/**
 * English strings (default).
 */
val EnglishStrings = AppStrings(
    isChinese = false,
    appName = "MengPaw",
    settings = "Settings",
    back = "Back",

    systemBanner = "Agent is ready. Describe the task you want to accomplish.",
    inputPlaceholder = "Describe a task for the Agent...",
    commandOutputLabel = "Command output",
    commandFailedLabel = "Command failed",
    roleRoutingTitle = "Role Model Routing (Combined Arms / Swarm)",
    thinking = "🤔 Thinking...",
    agentLabel = "Agent",
    stop = "Stop",
    send = "Send",

    llmProvider = "LLM Provider",
    apiEndpoint = "API Endpoint",
    apiKey = "API Key",
    apiKeyShow = "Show",
    apiKeyHide = "Hide",
    model = "Model",

    agent = "Agent",
    maxSteps = "Max Steps",
    maxStepsDesc = "Maximum ReAct iterations before forced stop",
    llmConcurrency = "LLM Concurrency",
    llmConcurrencyDesc = "Max simultaneous LLM API calls (1-50)",

    appearance = "Appearance",
    darkTheme = "Dark Theme",
    darkThemeDesc = "Light / Dark / Follow System",
    language = "Language",
    languageDesc = "Switch UI language",
    languageZh = "中文",
    languageEn = "English",

    agentLanguage = "Agent Language",
    agentLanguageDesc = "Language for Agent's thinking and responses",
    agentLanguageFollowUi = "Follow UI",
    agentLanguageChinese = "中文",
    agentLanguageEnglish = "English",

    expandFileSection = "File Upload",
    expandModeSection = "Execution Mode",
    expandPluginSection = "Plugin Tools",
    filePickImage = "Image",
    filePickDocument = "Document",
    filePickFile = "File",
    filePickCamera = "Camera",
    dragHint = "Long-press to reorder",

    tagModeMission = "/Mission",
    tagModeResearch = "/Research",
    tagModeTranslate = "/Translate",
    tagModeSilent = "/Silent",
    tagDismiss = "Remove",
    mentionHint = "@mention an agent...",

    placeholderMission = "Describe a complex task for sub-agents to decompose...",
    placeholderResearch = "Enter a topic for deep research with source verification...",
    placeholderTranslate = "Enter text to translate...",
    placeholderSilent = "Describe a background task to run silently...",

    about = "About",
    version = "Version",
    core = "Core",
    design = "Design",
    resetDefaults = "Reset to Defaults",

    // Sidebar
    sidebarAgents = "Agents",
    sidebarCurrent = "Current",
    sidebarFeatures = "Features",
    sidebarFrameworkDirectory = "Framework Directory",
    sidebarFrameworkStatus = "Framework Status",
    sidebarNoFriends = "Your agents have no friends yet",
    sidebarPlugins = "Plugins",
    sidebarSettings = "Settings",

    // General
    cancel = "Cancel",
    delete = "Delete",

    // Settings - System
    systemAttribution = "Open Source Attribution",
    systemAttributionDesc = "Code references, inspiration sources, and license compliance",
    systemBackground = "Background Running",
    systemBackgroundMode = "Background Mode",
    systemBackgroundPowerSaver = "Power Saver Mode",
    systemBackgroundPowerSaverDesc = "Reduce background poll frequency and animation frame rate to extend battery life",
    systemBatteryIgnored = "Battery optimization ignored",
    systemBatteryIgnoredDesc = "System will not restrict background running when screen is off",
    systemBatteryNotIgnored = "Battery optimization not ignored",
    systemBatteryNotIgnoredDesc = "Tap to jump to system settings, disable to prevent screen-off restrictions",
    systemCacheSaved = "Cache Saved",
    systemContactUs = "Contact Us",
    systemCopyright = "Copyright",
    systemCopyrightDesc = "© 2026 ShenZhen wowblue culture and technology CO.,LTD.",
    systemDaily = "Daily",
    systemEstimatedSavings = "Est. Savings",
    systemGoToBatterySettings = "Go to Settings →",
    systemLegalContact = "Legal & Contact",
    systemLicense = "License",
    systemMonthly = "Monthly",
    systemNoTokenData = "No token usage data yet. Recording starts automatically.",
    systemTimezone = "Timezone",
    systemTimezoneAuto = "Auto",
    systemTimezoneShanghai = "Shanghai",
    systemTokenStats = "Token Usage Statistics",
    systemTotalUsage = "Total Usage",
    systemWeekly = "Weekly",

    // Settings - Agent
    agentAddHumanTouch = "Add Human Touch",
    agentAddScheduled = "Add Scheduled",
    agentApiReturnedModels = "API Returned Models",
    agentFromGlobalPool = "Install from Global Tool Pool",
    agentFromSkillPool = "Install from Global Skill Pool",
    agentInstallHelp = "Three methods: ① Install from global pool ② Agent auto-discovers and installs ③ Manual download with path, Agent installs",
    agentLastFired = "Last fired: %s",
    agentLoopMode = "Loop Mode",
    agentLoopModeDesc = "Agent automatically selects the appropriate execution mode based on task complexity.",
    agentNoProvider = "No API provider added yet. Please go to Framework Settings to configure.",
    agentNoSkills = "No local skills yet. Use skill.pull to fetch from the global pool, or skill.create to author one.",
    agentNoTriggers = "No triggers yet. Add scheduled tasks for Agent to execute automatically.",
    agentParams = "Agent Parameters",
    agentPlugins = "Agent Plugins",
    agentProviderModel = "Provider & Model",
    agentRefreshFileList = "Refresh file list",
    agentRefreshModels = "Refresh Model List",
    agentRemainingCount = "... and %d more",
    agentSelectModel = "Select Model",
    agentShellTimeout = "Shell Command Timeout",
    agentShellTimeoutDesc = "Max execution time per command (seconds)",
    agentSkills = "Agent Skills",
    agentSkillPool = "Global Skill Pool",
    agentTools = "Agent Tools",
    agentTriggerHuman = "Human",
    agentTriggers = "Scheduled Tasks & Triggers",
    agentTriggerScheduled = "Scheduled",
    agentWorkspaceFiles = "Workspace Files",

    // Settings - Framework
    frameworkAddProvider = "Add API Provider",
    frameworkApiProvider = "API Provider",
    frameworkCollapseList = "Collapse Provider List",
    frameworkContextStrategy = "Context Strategy",
    frameworkContextStrategyDesc = "Built-in · Reasonix 4-Level Fold",
    frameworkEditConnection = "Edit Connection",
    frameworkGlobalPlugins = "Global Plugins",
    frameworkGlobalSkills = "Global Skills",
    frameworkGlobalTools = "Global Tools",
    frameworkMemoryBackend = "Memory Backend",
    frameworkMemoryBackendDesc = "Built-in · Markdown files",
    frameworkMemoryManagement = "Memory Management",
    frameworkNewConnection = "New Connection",
    frameworkPluginManagement = "Plugin Management",
    frameworkPluginManagementDesc = "Browse, install, manage Agent plugins",
    frameworkProviderLabel = "Provider",
    frameworkSaveConnection = "Save",
    frameworkTestConnection = "Test",
    frameworkTestingConnection = "Testing connection...",

    // Settings - Sidebar tabs
    sidebarSettingsAgent = "Agent Settings",
    sidebarSettingsFramework = "Framework Settings",
    sidebarSettingsSystem = "System Settings",

    // Security
    securityAgentDocs = "Agent Documents",
    securityFingerprint = "Fingerprint: %s",
    securityFileIntegrity = "File Integrity Protection",
    securityFileIntegrityDesc = "Enabled — Protects core directories from modification",
    securityKernelDir = "Kernel Directory",
    securityKernelIntegrity = "Kernel Integrity Protection",
    securityKernelIntegrityDesc = "Enabled — Prevents Agent from executing dangerous commands",
    securityKeyStore = "Key Store",
    securityNoTrusted = "No trusted framework devices yet. Add via ACP pairing.",
    securityPluginCache = "Plugin Cache",
    securityPluginIntegrity = "Plugin Integrity Protection",
    securityPluginIntegrityDesc = "Enabled — Verifies plugin signatures and version compatibility",
    securityProtectedDirs = "Protected Directories:",
    securityRules = "Security Rules",
    securityTrusted = "Trusted",
    securityTrustedCount = "Trusted %d framework devices",
    securityTrustedFramework = "Framework Trust List",

    pluginMarketTitle = "Plugin Management",
    forceRefresh = "Force Refresh",
    marketTab = "Market",
    installedTab = "Installed",
    noPluginsAvailable = "No plugins available",
    noInstalledPlugins = "No installed plugins",
    refreshHint = "Tap refresh to load the plugin list",
    availablePrefix = "Available: ",
    installedPrefix = "Installed: ",
    activePrefix = "Active: ",
    builtinBadge = "Built-in",
    embeddedBadge = "Embedded",
    activeBadge = "Active",
    disabledBadge = "Disabled",
    notPublishedBadge = "Not Published",
    uninstall = "Uninstall",
    install = "Install",
    verifying = "Verifying...",
    installedBadge = "Installed",
    failedBadge = "Failed",
    retry = "Retry",
    pluginNotFound = "Plugin not found: ",
    notInstalledBadge = "Not Installed",
    typePrefix = "Type: ",
    commandsLabel = "Commands",
    permissionsLabel = "Permissions",
    enable = "Enable",
    disable = "Disable",
    installPlugin = "Install Plugin",
    errorPrefix = "Error: ",
    cronTitle = "CRON Scheduled Task",
    cronExpression = "Cron Expression",
    cronPlaceholder = "min hour dom mon dow  e.g. 0 9 * * *",
    cronHint = "Let the Agent compute the schedule, e.g. \"generate yesterday's digest every 9am\"",
    actionLabel = "Action",
    actionPlaceholder = "Describe the task for the Agent...",
    cronTip = "💡 Tell the Agent in chat: \"generate yesterday's digest every 9am\" — it will call self.trigger add",
    add = "Add",
    scheduleTitle = "SCHEDULE Window Trigger",
    scheduleParams = "Parameters",
    scheduleParamsPlaceholder = "window,count=N,interval=M",
    scheduleFormatHint = "Format: HH:MM-HH:MM,count=N,interval=M  e.g. 08:00-22:00,count=3,interval=60",
    scheduleTip = "💡 Tell the Agent in chat: \"chat with me 4 times between 10am-6pm daily, ≥1h apart\" — it will call self.trigger add schedule",
    noEntries = "No entries",
    noDocs = "No docs",
    agentToolsDesc = "Agent-specific command tools, only available to this agent. Global commands via self.tools.",
    noToolsConfigured = "No agent-specific tools configured. Uses the global tool pool (self.tools).",
    agentSkillsDesc = "Skills loaded for this agent (Markdown scripts). Run via skill.run <name>.",
    noWorkspaceDocs = "No workspace documents",
    deleteDoc = "Delete Document",
    deleteConfirm = "Delete this document? This cannot be undone.",
    roleRoutingEmpty = "Save at least one provider above before assigning roles.",
    defaultMainModel = "Default (main model)",
    optimizedBadge = "Optimized",
    apiReturned = "From API",
    builtinCategory = "Built-in",
    officialCategory = "Official",
    customCategory = "Custom",
    lightTheme = "Light",
    systemTheme = "System",
    notifPersistent = "Persistent Notification",
    silentRunning = "Silent Running",
    foregroundOnly = "Foreground Only",
    notifPersistentDesc = "Status bar icon, strongest keep-alive (recommended)",
    silentRunningDesc = "Hidden notification icon, foreground service still active",
    foregroundOnlyDesc = "Service released on exit, most battery-efficient",
    rolePlanner = "Planner",
    roleWorker = "Worker",
    roleVerifier = "Verifier",
    roleSynthesizer = "Synthesizer",
    roleWorkerAlt = "Alternate Worker"
)

/**
 * Chinese (Simplified) strings.
 */
val ChineseStrings = AppStrings(
    isChinese = true,
    appName = "MengPaw",
    settings = "设置 (Settings)",
    back = "返回",

    systemBanner = "Agent 已就绪。描述你想要完成的任务。",
    inputPlaceholder = "描述一个任务给 Agent...",
    commandOutputLabel = "命令输出",
    commandFailedLabel = "命令执行失败",
    roleRoutingTitle = "角色模型路由（步坦协同/火种）",
    thinking = "🤔 思考中 (Thinking)...",
    agentLabel = "Agent",
    stop = "停止",
    send = "发送",

    llmProvider = "LLM 提供商 (Provider)",
    apiEndpoint = "API 地址 (Endpoint)",
    apiKey = "API 密钥 (Key)",
    apiKeyShow = "显示",
    apiKeyHide = "隐藏",
    model = "模型 (Model)",

    agent = "Agent",
    maxSteps = "最大步数 (Max Steps)",
    maxStepsDesc = "ReAct 循环最大迭代次数",
    llmConcurrency = "LLM 并发上限",
    llmConcurrencyDesc = "同时进行的 LLM API 调用数量上限 (1-50)",

    appearance = "外观",
    darkTheme = "深色主题 (Dark Theme)",
    darkThemeDesc = "亮色 / 暗色 / 跟随系统",
    language = "语言 (Language)",
    languageDesc = "切换界面语言",
    languageZh = "中文",
    languageEn = "English",

    agentLanguage = "Agent 语言",
    agentLanguageDesc = "控制 Agent 思考和输出的语言",
    agentLanguageFollowUi = "跟随界面",
    agentLanguageChinese = "中文",
    agentLanguageEnglish = "English",

    expandFileSection = "文件提交",
    expandModeSection = "执行模式",
    expandPluginSection = "插件工具",
    filePickImage = "图片",
    filePickDocument = "文档",
    filePickFile = "文件",
    filePickCamera = "拍照",
    dragHint = "长按拖拽排序",

    tagModeMission = "/Mission",
    tagModeResearch = "/Research",
    tagModeTranslate = "/Translate",
    tagModeSilent = "/Silent",
    tagDismiss = "移除",
    mentionHint = "@智能体名称...",

    placeholderMission = "输入一个需要子智能体进行拆解执行的复杂任务",
    placeholderResearch = "输入需要深度调研的课题，将进行多轮搜索与交叉验证",
    placeholderTranslate = "输入需要翻译的内容",
    placeholderSilent = "输入后台静默执行的任务，完成后推送结果",

    about = "关于",
    version = "版本",
    core = "内核 (Core)",
    design = "设计 (Design)",
    resetDefaults = "恢复默认设置",

    // Sidebar
    sidebarAgents = "智能体",
    sidebarCurrent = "当前",
    sidebarFeatures = "功能",
    sidebarFrameworkDirectory = "框架通讯录",
    sidebarFrameworkStatus = "框架状态",
    sidebarNoFriends = "你的智能体还没有朋友",
    sidebarPlugins = "插件管理",
    sidebarSettings = "设置",

    // General
    cancel = "取消",
    delete = "删除",

    // Settings - System
    systemAttribution = "开源声明与致谢",
    systemAttributionDesc = "代码参考、灵感来源与许可合规",
    systemBackground = "后台运行",
    systemBackgroundMode = "后台运行策略",
    systemBackgroundPowerSaver = "后台省电模式",
    systemBackgroundPowerSaverDesc = "降低后台轮询频率和动画帧率，延长续航",
    systemBatteryIgnored = "已忽略电池优化",
    systemBatteryIgnoredDesc = "系统不会在息屏时限制后台运行",
    systemBatteryNotIgnored = "电池优化未忽略",
    systemBatteryNotIgnoredDesc = "点击跳转系统设置，关闭后可防止息屏限制",
    systemCacheSaved = "缓存节省",
    systemContactUs = "联系我们",
    systemCopyright = "版权声明",
    systemCopyrightDesc = "© 2026 深圳哇蓝文化科技有限公司",
    systemDaily = "每日",
    systemEstimatedSavings = "预估节省",
    systemGoToBatterySettings = "前往设置 →",
    systemLegalContact = "法律与联系",
    systemLicense = "许可证",
    systemMonthly = "每月",
    systemNoTokenData = "暂无 Token 用量数据。开始使用后自动记录。",
    systemTimezone = "时区",
    systemTimezoneAuto = "自动",
    systemTimezoneShanghai = "上海",
    systemTokenStats = "Token 用量统计",
    systemTotalUsage = "总用量",
    systemWeekly = "每周",

    // Settings - Agent
    agentAddHumanTouch = "添加真人感",
    agentAddScheduled = "添加定时",
    agentApiReturnedModels = "API 返回模型",
    agentFromGlobalPool = "从全局工具池安装",
    agentFromSkillPool = "从全局技能池安装",
    agentInstallHelp = "三种安装方式：①从全局工具池安装 ②Agent 自行搜索下载安装 ③用户手动下载并提供路径，Agent 自行安装",
    agentLastFired = "上次触发: %s",
    agentLoopMode = "Loop 模式",
    agentLoopModeDesc = "Agent 会根据任务复杂度自动选择合适的执行模式，无需手动切换。",
    agentNoProvider = "尚未添加 API 供应商，请先前往「框架设置」配置",
    agentNoSkills = "该智能体尚未拉取本地技能，可从全局技能池 skill.pull 拉取，或 skill.create 创建。",
    agentNoTriggers = "暂无触发器。添加定时任务让 Agent 在指定时间自动执行。",
    agentParams = "Agent 参数",
    agentPlugins = "Agent 插件",
    agentProviderModel = "供应商 & 模型",
    agentRefreshFileList = "刷新文件列表",
    agentRefreshModels = "刷新模型列表",
    agentRemainingCount = "... 还有 %d 个",
    agentSelectModel = "选择模型",
    agentShellTimeout = "Shell 命令超时",
    agentShellTimeoutDesc = "单个命令最长执行时间（秒）",
    agentSkills = "智能体技能(Agent Skills)",
    agentSkillPool = "全局技能池",
    agentTools = "智能体工具(Agent Tools)",
    agentTriggerHuman = "真人",
    agentTriggers = "定时任务 & 触发器",
    agentTriggerScheduled = "定时",
    agentWorkspaceFiles = "工作区文件",

    // Settings - Framework
    frameworkAddProvider = "新增API供应商",
    frameworkApiProvider = "API供应商",
    frameworkCollapseList = "收起API供应商列表",
    frameworkContextStrategy = "上下文策略",
    frameworkContextStrategyDesc = "内置 · Reasonix 四级折叠",
    frameworkEditConnection = "编辑连接",
    frameworkGlobalPlugins = "全局插件",
    frameworkGlobalSkills = "全局技能(Skills)",
    frameworkGlobalTools = "全局工具(Tools)",
    frameworkMemoryBackend = "记忆管理后端",
    frameworkMemoryBackendDesc = "内置 · Markdown 文件",
    frameworkMemoryManagement = "记忆管理",
    frameworkNewConnection = "新增连接",
    frameworkPluginManagement = "插件管理",
    frameworkPluginManagementDesc = "浏览、安装、管理 Agent 插件",
    frameworkProviderLabel = "供应商",
    frameworkSaveConnection = "保存",
    frameworkTestConnection = "测试",
    frameworkTestingConnection = "正在测试连接...",

    // Settings - Sidebar tabs
    sidebarSettingsAgent = "智能体设置",
    sidebarSettingsFramework = "框架设置",
    sidebarSettingsSystem = "系统设置",

    // Security
    securityAgentDocs = "Agent 文档",
    securityFingerprint = "指纹: %s",
    securityFileIntegrity = "文件完整性防护",
    securityFileIntegrityDesc = "已启用 — 保护核心目录不被修改",
    securityKernelDir = "内核目录",
    securityKernelIntegrity = "内核完整性防护",
    securityKernelIntegrityDesc = "已启用 — 阻止 Agent 执行危险命令",
    securityKeyStore = "密钥存储",
    securityNoTrusted = "暂无受信任的框架设备。通过 ACP 配对添加。",
    securityPluginCache = "插件缓存",
    securityPluginIntegrity = "插件完整性防护",
    securityPluginIntegrityDesc = "已启用 — 验证插件签名和版本兼容性",
    securityProtectedDirs = "受保护的目录：",
    securityRules = "安全规则",
    securityTrusted = "已信任",
    securityTrustedCount = "已信任 %d 个框架设备",
    securityTrustedFramework = "框架信任列表",

    pluginMarketTitle = "插件管理",
    forceRefresh = "强制刷新",
    marketTab = "市场",
    installedTab = "已安装",
    noPluginsAvailable = "暂无可用插件",
    noInstalledPlugins = "暂无已安装插件",
    refreshHint = "点击刷新获取插件列表",
    availablePrefix = "可用: ",
    installedPrefix = "已安装: ",
    activePrefix = "活跃: ",
    builtinBadge = "内置",
    embeddedBadge = "已嵌入",
    activeBadge = "活跃",
    disabledBadge = "已禁用",
    notPublishedBadge = "暂未发布",
    uninstall = "卸载",
    install = "安装",
    verifying = "校验中...",
    installedBadge = "已安装",
    failedBadge = "失败",
    retry = "重试",
    pluginNotFound = "插件未找到: ",
    notInstalledBadge = "未安装",
    typePrefix = "类型: ",
    commandsLabel = "命令列表",
    permissionsLabel = "权限",
    enable = "启用",
    disable = "禁用",
    installPlugin = "安装插件",
    errorPrefix = "错误: ",
    cronTitle = "CRON 定时任务",
    cronExpression = "Cron 表达式",
    cronPlaceholder = "分 时 日 月 周  例: 0 9 * * *",
    cronHint = "时间参数让 Agent 帮你算，例如：帮我每天早上9点生成昨日摘要",
    actionLabel = "执行动作",
    actionPlaceholder = "描述 Agent 需要执行的任务...",
    cronTip = "💡 在聊天框告诉 Agent：帮我在每天早上9点生成昨日摘要 — Agent 会自动调用 self.trigger add 配置",
    add = "添加",
    scheduleTitle = "SCHEDULE 日程触发器",
    scheduleParams = "配置参数",
    scheduleParamsPlaceholder = "窗口,count=N,interval=M",
    scheduleFormatHint = "格式: HH:MM-HH:MM,count=N,interval=M  例: 08:00-22:00,count=3,interval=60",
    scheduleTip = "💡 在聊天框告诉 Agent：帮我在每天上午10点到下午6点之间找我聊4次天，间隔至少1小时 — Agent 会自动调用 self.trigger add schedule 配置",
    noEntries = "暂无条目",
    noDocs = "暂无文档",
    agentToolsDesc = "该 Agent 专属的命令工具，仅在当前 Agent 可用。全局命令通过 self.tools 查看。",
    noToolsConfigured = "暂未配置专属工具。Agent 使用全局工具池（self.tools）中的命令。",
    agentSkillsDesc = "该 Agent 本地已加载的技能，Markdown 剧本格式。使用 skill.run <name> 执行。",
    noWorkspaceDocs = "工作区暂无文档",
    deleteDoc = "删除文档",
    deleteConfirm = "确定删除此文档？此操作不可恢复。",
    roleRoutingEmpty = "请先在上方保存至少一个模型连接，再为角色分配模型。",
    defaultMainModel = "默认（主模型）",
    optimizedBadge = "已优化",
    apiReturned = "API 返回",
    builtinCategory = "内置",
    officialCategory = "官方",
    customCategory = "自建",
    lightTheme = "亮色",
    systemTheme = "跟随系统",
    notifPersistent = "通知栏常驻",
    silentRunning = "静默运行",
    foregroundOnly = "仅前台使用",
    notifPersistentDesc = "状态栏显示图标，保活最强，推荐",
    silentRunningDesc = "隐藏通知图标，前台服务仍在后台",
    foregroundOnlyDesc = "退出时释放服务，最省电",
    rolePlanner = "规划器 (拆解)",
    roleWorker = "执行器 (worker)",
    roleVerifier = "验收器 (verifier)",
    roleSynthesizer = "合成器 (synthesizer)",
    roleWorkerAlt = "备用执行器 (worker.alt)"
)
