// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial

package com.mengpaw.kernel.agent

import com.mengpaw.kernel.error.ErrorCollector
import com.mengpaw.kernel.namespace.SelfExecutor
import com.mengpaw.kernel.plugin.PluginManager
import com.mengpaw.kernel.plugin.pluginNamespaceFor
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * CLI.md 生成器 — 拆自 AgentDocManager.regenerateCliDoc (400 行文件拆分)。
 * 经 AgentDocManager.regenerateCliDoc 委托, 命令表常量读 [AgentCliDocTables]。
 */
internal class CliDocGenerator(private val manager: AgentDocManager) {

    /** Regenerate CLI.md — Agent's primary command reference with permission guides & tutorials. */
    internal fun regenerateCliDoc(pluginManager: PluginManager) {
        try { manager.file(AgentDocType.CLI).atomicWriteText(buildString {
            appendLine("# MengPaw CLI 命令参考")
            appendLine()
            appendLine("> 本文档是 Agent 的主要命令参考。Agent 在执行任何操作前应查阅本文档，")
            appendLine("> 了解所需命令、权限和前置条件。所有提醒义务由 Agent 承担。")
            appendLine("> 生成时间: ${SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).format(Date())}")
            appendLine("> 活跃插件: ${pluginManager.activeCount()}")
            appendLine("> 命令指纹: ${manager.commandFingerprint(pluginManager)}")
            appendLine()

            // ── Built-in Commands ──
            appendLine("## 内置命令 (始终可用)")
            appendLine()
            appendLine("### self — Agent 自我管理")
            appendLine("| 命令 | 用法 | 说明 | 权限 |")
            appendLine("|------|------|------|------|")
            SelfExecutor.commands.keys.sorted().forEach { name ->
                val full = "self.$name"
                val d = AgentDocManager.SELF_COMMANDS.firstOrNull { it.first == name }
                if (d != null) appendLine("| $full | ${d.second} | ${d.third} | 无 |")
                else appendLine("| $full | $full | 见 self.search 获取用法 | 无 |")
            }
            appendLine()
            appendLine("### evolution — Agent 进化 (从失败中学习)")
            appendLine("| 命令 | 用法 | 说明 | 权限 |")
            appendLine("|------|------|------|------|")
            appendLine("| evolution.audit | evolution.audit | 进化绩效: 失败分布/复现率/教训 | 无 |")
            appendLine("| evolution.report | evolution.report <描述> | 框架缺陷反馈给开发者 (落盘+推送) | 无 |")
            appendLine("| evolution.learn.command | evolution.learn.command <命令> <描述> [--keywords 词,词] | 丰富指令集 (登记正确用法/同义词) | 无 |")
            appendLine("| evolution.reactions | evolution.reactions | 查看用户反应档案 (用户分身数据源) | 无 |")
            appendLine("| evolution.mark-corrected | evolution.mark-corrected <id> | 标记失败模式已沉淀修正 | 无 |")
            appendLine()
            appendLine("> 失败后系统自动注入金字塔省察引导 (L1 事实 → L2 归因 → L3 用户视角 → L4 进化), 处置动作: 常识错用 agent.memory.keep, 行为错改 soul.md (agent.write), 指令错用 evolution.learn.command 或 self.search。")
            appendLine()
            appendLine("## 网络端口参考")
            appendLine()
            appendLine(com.mengpaw.kernel.ports.Ports.describe("zh"))
            appendLine()

            appendLine("### plugin — 插件/工具/技能管理")
            appendLine("| 命令 | 用法 | 说明 | 权限 |")
            appendLine("|------|------|------|------|")
            appendLine("| plugin.marketplace | plugin.marketplace [--refresh] | 浏览插件市场 | 无 |")
            appendLine("| plugin.search | plugin.search <关键词> | 搜索插件 | 无 |")
            appendLine("| plugin.install | plugin.install <插件ID> | 下载+验证+安装+激活 | 无 |")
            appendLine("| plugin.uninstall | plugin.uninstall <插件ID> | 卸载插件 | 无 |")
            appendLine("| plugin.list | plugin.list | 已安装列表 | 无 |")
            appendLine("| plugin.info | plugin.info <插件ID> | 插件详情 | 无 |")
            appendLine("| plugin.enable | plugin.enable <插件ID> | 启用 | 无 |")
            appendLine("| plugin.disable | plugin.disable <插件ID> | 停用 | 无 |")
            appendLine("| plugin.update | plugin.update <插件ID> | 检查更新 | 无 |")
            appendLine("| plugin.upgrade | plugin.upgrade --all | 升级全部 | 无 |")
            appendLine("| plugin.verify | plugin.verify <插件ID> \\| plugin.verify --all | 校验插件文件完整性 | 无 |")
            appendLine("| plugin.auto | plugin.auto <wake\\|sleep\\|status\\|sleep-idle> | 插件省电管理 | 无 |")
            appendLine()

            appendLine("### agent — Agent 文档")
            appendLine("| 命令 | 用法 | 说明 |")
            appendLine("|------|------|------|")
            manager.registeredAgentCommands.forEach { name ->
                val full = "agent.$name"
                val d = AgentDocManager.AGENT_COMMANDS.firstOrNull { it.first == name }
                if (d != null) appendLine("| $full | ${d.second} | ${d.third} |")
                else appendLine("| $full | $full | 见 self.search $full 获取用法 |")
            }
            appendLine()

            appendLine("### sys — 系统信息 (Android 设备能力)")
            appendLine("| 命令 | 说明 | 权限 |")
            appendLine("|------|------|------|")
            appendLine("| sys.device | 设备信息 (型号/厂商/SDK) | 无 |")
            appendLine("| sys.battery | 电量/充电/温度 | 无 |")
            appendLine("| sys.network | 网络类型/信号 | 无 |")
            appendLine("| sys.wifi | WiFi 详情 | 无 |")
            appendLine("| sys.wifi.enable | WiFi 开关 | 无 |")
            appendLine("| sys.bluetooth | 蓝牙状态 | 无 |")
            appendLine("| sys.location | GPS 定位 | **需位置权限** |")
            appendLine("| sys.cpu | CPU 使用率/核心 | 无 |")
            appendLine("| sys.memory | 内存用量 | 无 |")
            appendLine("| sys.storage | 存储空间 | 无 |")
            appendLine("| sys.camera | 摄像头信息 | **需相机权限** |")
            appendLine("| sys.sensors | 传感器列表 | 无 |")
            appendLine("| sys.display | 屏幕参数 | 无 |")
            appendLine("| sys.telephony | 电话信息/运营商 | **需电话权限** |")
            appendLine("| sys.power | 电源状态 | 无 |")
            appendLine("| sys.power.save | 省电模式 | 无 |")
            appendLine("| sys.screen.on | 亮屏/唤醒 | 无 |")
            appendLine("| sys.screen.off | 熄屏 | 无 |")
            appendLine("| sys.screen.brightness | 设置亮度 | 无 |")
            appendLine("| sys.volume | 音量 | 无 |")
            appendLine("| sys.volume.set | 设置音量 | 无 |")
            appendLine("| sys.vibrate | 震动 | 无 |")
            appendLine("| sys.ringtone.play | 播放铃声 | 无 |")
            appendLine("| sys.apps | 已安装应用 | **需应用列表权限** |")
            appendLine("| sys.app.launch | 启动应用 | 无 |")
            appendLine("| sys.app.uninstall | 卸载应用 | 无 |")
            appendLine("| sys.app.info | 应用详情 | 无 |")
            appendLine("| sys.browser.open | 打开浏览器 | 无 |")
            appendLine("| sys.clipboard | 读取剪贴板 | 无 |")
            appendLine("| sys.clipboard.set | 写入剪贴板 | 无 |")
            appendLine("| sys.intent.open | 打开链接/应用 | 无 |")
            appendLine("| sys.intent.share | 分享文本 | 无 |")
            appendLine("| sys.intent.view | 查看文件 | 无 |")
            appendLine("| sys.notification.id | 通知渠道 ID | **需通知权限** |")
            appendLine("| sys.notification.send | 发送通知 | **需通知权限** |")
            appendLine("| sys.notification.cancel | 取消通知 | 无 |")
            appendLine("| sys.alarm.set | 设置闹钟 | 无 |")
            appendLine("| sys.permission.list | 列出权限 | 无 |")
            appendLine("| sys.permission.check | 检查权限 | 无 |")
            appendLine("| sys.permission.request | 申请权限 | 无 |")
            appendLine("| sys.overlay.show | 显示悬浮窗 | **需悬浮窗权限** |")
            appendLine("| sys.overlay.hide | 隐藏悬浮窗 | 无 |")
            appendLine("| sys.overlay.update | 更新悬浮窗 | 无 |")
            appendLine("| sys.calendar.add | 添加日历事件 | **需日历权限** |")
            appendLine("| sys.calendar.list | 列出日历事件 | **需日历权限** |")
            appendLine("| sys.calendar.delete | 删除日历事件 | **需日历权限** |")
            appendLine("| sys.calendar.calendars | 列出日历账户 | **需日历权限** |")
            appendLine("| sys.screenshot | 截图 | 无 |")
            appendLine("| sys.screenrecord.start | 开始录屏 | 无 |")
            appendLine("| sys.screenrecord.stop | 停止录屏 | 无 |")
            appendLine("| sys.camera.photo | 拍照 (需用户确认) | **需相机权限** |")
            appendLine()

            // ── Plugin commands ──
            appendLine("## 插件命令 (按需安装)")
            appendLine()
            pluginManager.getActivePlugins().forEach { plugin ->
                val ns = pluginNamespaceFor(plugin.metadata.id)
                val perms = plugin.metadata.permissions.ifEmpty { listOf("无") }
                appendLine("### $ns — ${plugin.metadata.name}")
                appendLine("| 命令 | 用法 | 权限 |")
                appendLine("|------|------|------|")
                plugin.commands.keys.sorted().forEach { cmd ->
                    appendLine("| $ns.$cmd | $ns $cmd | ${perms.joinToString(", ")} |")
                }
                appendLine()
            }

            // ── Tutorials ──
            appendLine("---")
            appendLine()
            appendLine("## Agent 操作指南 (展示给用户)")
            appendLine()
            appendLine("Agent 负责提醒用户完成以下手动操作。当检测到所需能力缺失时，" +
                "Agent 应主动向用户展示对应的教程章节。")
            appendLine()

            appendLine("### 启用 USB 调试")
            appendLine("1. 打开 设置 → 关于手机")
            appendLine("2. 连续点击「版本号」7 次，直到提示「开发者模式已开启」")
            appendLine("3. 返回 设置 → 系统 → 开发者选项")
            appendLine("4. 开启「USB 调试」")
            appendLine("5. 连接电脑后，手机上点击「允许」")
            appendLine()

            appendLine("### 获取 Root 权限")
            appendLine("Root 权限允许 Agent 执行系统级操作（如 ui.click 真实触控）。")
            appendLine("**警告：Root 会增加安全风险。**")
            appendLine("1. 确认设备 Bootloader 已解锁")
            appendLine("2. 安装 Magisk Manager")
            appendLine("3. 通过 Magisk 修补 boot.img 并刷入")
            appendLine("4. 重启后在 Magisk 中授权 MengPaw")
            appendLine("5. root 后可使用 `proc.exec` 命令（需先解除沙箱禁用）")
            appendLine()

            appendLine("### 授予无障碍权限")
            appendLine("`ui.*` 命令需要无障碍服务才能执行真实触控：")
            appendLine("1. 打开 设置 → 无障碍 → 已安装的应用")
            appendLine("2. 找到 MengPaw，开启无障碍服务")
            appendLine("3. 确认授权对话框")
            appendLine()

            appendLine("### 安装插件/Tools/Skills")
            appendLine("Agent 会在需要时自动检测缺失的能力，并建议安装对应的插件：")
            appendLine("1. Agent 执行命令 → 返回 \"Unknown command: xxx\"")
            appendLine("2. Agent 调用 `plugin.search xxx` 查找匹配插件")
            appendLine("3. Agent 向用户展示插件信息和权限要求")
            appendLine("4. 用户确认后，Agent 执行 `plugin.install <插件ID>`")
            appendLine("5. 插件自动激活，命令即可用")
            appendLine()

            appendLine("### 切换搜索引擎 (MP浏览器)")
            appendLine("点击浏览器搜索框左侧的引擎图标循环切换，或在设置中勾选/排序。")
            appendLine()

            appendLine("### 插件省电管理 (Power-Aware Plugin)")
            appendLine("Agent 在后台静默运行时自动管理插件以降低功耗：")
            appendLine("- `plugin.auto sleep <id>` — 休眠指定插件，释放内存和线程")
            appendLine("- `plugin.auto wake <id>` — 唤醒插件（执行任务前自动调用）")
            appendLine("- `plugin.auto sleep-idle` — 休眠所有非核心插件（self/plugin/agent 除外）")
            appendLine("- `plugin.auto status` — 查看所有插件功耗状态")
            appendLine("- Agent 应在任务完成后休眠非必要插件，执行前自动唤醒所需插件")
            appendLine("- 后台空闲 > 10min 建议执行 `plugin.auto sleep-idle`")
            appendLine()

            appendLine("### 插件隔离 (Plugin Isolation)")
            appendLine("Agent 可以通过启停插件来隔离不同 Agent 的权限和能力：")
            appendLine("- `plugin.disable <插件ID>` — 停用插件，Agent 无法调用其命令")
            appendLine("- `plugin.enable <插件ID>` — 重新启用插件")
            appendLine("- 停用的插件仍保留已安装状态，配置和数据不丢失")
            appendLine("- Agent 可使用此机制限制其他 Agent 的权限范围")
            appendLine("- 多 Agent 场景：为每个 Agent 启用不同的插件组合，实现能力隔离")
            appendLine()

            appendLine("### 多Agent协作 (Hermes)")
            appendLine("通过 hermes-plugin 实现多 Agent 对话和任务委派：")
            appendLine("- `hermes.role <角色描述>` — 设定自身角色（如：研究员、代码审查员）")
            appendLine("- `hermes.discover` — 发现本地可用的其他 Agent")
            appendLine("- `hermes.team invite <id> <role>` — 邀请 Agent 加入团队")
            appendLine("- `hermes.delegate <agent> <任务>` — 委派任务给团队成员")
            appendLine("- `hermes.ask <agent> <问题>` — 向其他 Agent 提问")
            appendLine("- `hermes.memo [内容]` — 团队共享记忆")
            appendLine("- 委派的任务写入目标 Agent 的 inbox/ 目录")
            appendLine("- 团队信息存储在 Agent文档/team/ 目录")
            appendLine()

            appendLine("### 广告拦截 (MP浏览器)")
            appendLine("菜单 → 广告拦截开关，默认开启。拦截 40+ 常见广告/追踪域名。")
            appendLine()

            appendLine("---")
            appendLine()
            appendLine("## 可用的插件/Tools/Skills 列表")
            appendLine()
            appendLine("Agent 可按需安装以下插件。使用 `plugin.install <ID>` 安装。")
            appendLine("完整命令与权限见 `plugin.info <ID>` 或 `self.tools <命名空间>`。")
            appendLine()
            appendLine("### 内置 (随 APK 预装, 仅可禁用)")
            appendLine()
            appendLine("| 插件ID | 命令命名空间 | 用途 |")
            appendLine("|--------|------------|------|")
            appendLine("| framework-plugin | framework.* | 外部框架接入/发现 |")
            appendLine("| fs-plugin | fs.* | 文件系统 |")
            appendLine("| net-plugin | net.* | 网络请求 |")
            appendLine("| memory-twin-plugin | twin.* | 记忆孪生/跨设备同步 |")
            appendLine("| skill-plugin | skill.* | 技能系统 |")
            appendLine("| clipboard-plugin | clipboard.* | 剪贴板 |")
            appendLine("| notification-plugin | notification.* | 通知 |")
            appendLine("| dev-plugin | dev.plugin.* | 插件开发工具 (create/audit/share) |")
            appendLine("| root-plugin | root.* | Root 权限 (最高权限) |")
            appendLine("| tools-plugin | tools.* | Agent 命令集 (import/ls/remove/search) |")
            appendLine("| dream-plugin | agent.dream | 梦境模式 — 记忆整理管道 (中期→长期) |")
            appendLine("| evolution-plugin | evolution.* | 智能体进化 — 失败模式库/省察引导/框架反馈 |")
            appendLine("| tavily-plugin | tavily.* | AI 搜索 (内置, 需 TAVILY_API_KEY 或 tavily.setup 配置) |")
            appendLine()
            appendLine("### 远程/按需安装")
            appendLine()
            appendLine("| 插件ID | 用途 |")
            appendLine("|--------|------|")
            appendLine("| tribe-plugin (hermes 兼容) | 部落协作/多Agent团队 |")
            appendLine("| update-plugin | 自动更新 |")
            appendLine("| translate-plugin | 翻译 |")
            appendLine("| error-report-plugin | 错误上报 |")
            appendLine("| render-plugin | API 生图 (需 API Key) |")
            appendLine("| comfy-plugin | ComfyUI 工作流 (默认端口 8188) |")
            appendLine("| workflow-plugin | 工作流编排 |")
            appendLine("| incubator-plugin | Agent 孵化器 |")
            appendLine("| browser-push/search/mcp/cdp/inspector-plugin | 浏览器扩展能力 |")
            appendLine()
            appendLine("### 嵌入 (UI 绑定, 不可安装/卸载)")
            appendLine()
            appendLine("| 插件ID | 用途 |")
            appendLine("|--------|------|")
            appendLine("| agent-mission-plugin | Mission 模式 |")
            appendLine("| agent-loop-plugin | Agent Loop 模式 |")
            appendLine()
            appendLine("端口与网络接口一览: `self.ports`。")
            appendLine()
            appendLine("### ⚠️ 生图参数准则 (Agent 必读)")
            appendLine("Agent 在设置生图参数前，**必须**查询社区公开信息，不可随意填写:")
            appendLine("1. 使用 tavily.search 或 net.curl 查询 Civitai (civitai.com) 上对应模型的推荐参数")
            appendLine("2. 参考 ComfyUI 官方文档 (docs.comfy.org)")
            appendLine("3. 常用安全范围: Steps=20~40, CFG=5~9, Sampler=euler_ancestral/dpm++_2m")
            appendLine("4. 无参考时使用保守值: Steps=25, CFG=7, Sampler=euler_ancestral")
            appendLine("5. API生图 (render.generate) 同样需要先查询模型推荐的 prompt 格式")
            appendLine()

            appendLine("## ComfyUI 工作流 CLI 参考")
            appendLine("| 命令 | 用法 | 说明 |")
            appendLine("|------|------|------|")
            appendLine("| comfy.nodes | comfy.nodes [category] | 查看可用节点（含参数警告） |")
            appendLine("| comfy.workflow create | comfy.workflow create <name> | 创建空工作流 |")
            appendLine("| comfy.workflow add | comfy.workflow add <wf> <id> <type> [params] | 添加节点 |")
            appendLine("| comfy.workflow connect | comfy.workflow connect <wf> <from:slot> <to:slot> | 连接节点 |")
            appendLine("| comfy.workflow show | comfy.workflow show <name> | 查看工作流JSON |")
            appendLine("| comfy.workflow list | comfy.workflow list | 列出所有工作流 |")
            appendLine("| comfy.run | comfy.run <wf> [api-url=...] | 提交到 ComfyUI API |")
            appendLine("| comfy.preview | comfy.preview <wf> | 在 MP浏览器预览结果 |")
            appendLine("| comfy.export | comfy.export <wf> json | 导出工作流 JSON |")
            appendLine()

            appendLine("## API 生图 CLI 参考")
            appendLine("| 命令 | 用法 | 说明 |")
            appendLine("|------|------|------|")
            appendLine("| render.models | render.models [replicate/stability/dalle] | 查看可用模型 |")
            appendLine("| render.generate | render.generate <backend> <model> prompt=... | 提交生图Job |")
            appendLine("| render.status | render.status [job-id] | 查询Job状态 |")
            appendLine("| render.preview | render.preview <job-id> | 在 MP浏览器预览结果 |")
            appendLine()
            appendLine("> 完整插件市场: `plugin.marketplace`")
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("*Agent CLI 参考 v0.2 · MengPaw*")
        })
        } catch (e: Exception) { ErrorCollector.report(e, "AgentDocManager.regenerateCliDoc") }
    }
}
