// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later

package com.mengpaw.kernel.agent

import com.mengpaw.kernel.DataPaths
import java.io.File

/**
 * Scroll context management — write-through + eviction index.
 *
 * Instead of summarizing evicted conversation spans (losing detail),
 * each evicted span is assigned a deterministic **headline** and stored
 * in an in-memory LRU index. The agent can later recall specific spans
 * via structured queries.
 *
 * Inspired by QwenPaw's Scroll Context Manager (Apache 2.0),
 * reimplemented for Android with LruCache + plain text persistence.
 */
class ScrollContextManager(
    private val agentName: String,
    private val maxHotSpans: Int = 128,
    private val maxSpanChars: Int = 6000
) {
    data class SpanEntry(
        val id: Int,
        val seqLo: Int,
        val seqHi: Int,
        val headline: String,
        val summary: String,   // first ~200 chars as extractive fallback
        val timestamp: Long = System.currentTimeMillis()
    )

    /** In-memory index: span ID → headline. Bounded by maxHotSpans via LRU eviction. */
    private val index = object : LinkedHashMap<Int, SpanEntry>(maxHotSpans, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<Int, SpanEntry>?): Boolean {
            if (size > maxHotSpans) {
                // Write through to cold storage before evicting
                eldest?.let { persistSpan(it.value) }
                return true
            }
            return false
        }
    }

    private var nextSpanId = 1
    private val coldDir = File(DataPaths.AGENTS, "$agentName/scroll")

    /**
     * Register an evicted span with a generated headline.
     * The headline should be generated by a cheap model call on the evicted text.
     */
    fun evictSpan(seqLo: Int, seqHi: Int, text: String, headline: String) {
        val summary = if (text.length <= 200) text else text.take(200) + "…"
        val entry = SpanEntry(nextSpanId++, seqLo, seqHi, headline, summary)
        synchronized(index) { index[entry.id] = entry }
    }

    /**
     * Recall spans matching a query by searching headlines and summaries.
     * Simple substring match — fast on in-memory data, no external index needed.
     */
    fun recall(query: String, maxResults: Int = 5): List<SpanEntry> {
        val q = query.lowercase()
        val results = mutableListOf<SpanEntry>()
        synchronized(index) {
            for (entry in index.values) {
                if (entry.headline.lowercase().contains(q) ||
                    entry.summary.lowercase().contains(q)) {
                    results.add(entry)
                    if (results.size >= maxResults) break
                }
            }
        }
        // Also search cold storage if online results < maxResults
        if (results.size < maxResults) {
            results.addAll(recallFromCold(q, maxResults - results.size))
        }
        return results
    }

    /** List all hot index entries (for display). */
    fun listIndex(): List<SpanEntry> = synchronized(index) { index.values.toList() }

    /** Total spans currently indexed (hot + cold). */
    fun indexSize(): Int = synchronized(index) { index.size } + countColdSpans()

    /** Format recall results for insertion into the conversation. */
    fun formatRecallResults(results: List<SpanEntry>): String {
        if (results.isEmpty()) return "（未找到相关历史记录）"
        return buildString {
            append("回忆的对话片段：\n")
            results.forEach { e ->
                append("  [${e.id}] ${e.headline}")
                if (e.summary.length > e.headline.length) {
                    append(" — ${e.summary.take(100)}")
                }
                append("\n")
            }
        }
    }

    // ── Cold storage: plain text file, one entry per line ──

    private fun persistSpan(entry: SpanEntry) {
        try {
            if (!coldDir.exists()) coldDir.mkdirs()
            File(coldDir, "scroll_index.txt").appendText(
                "${entry.id}\t${entry.seqLo}\t${entry.seqHi}\t${entry.headline}\t${entry.summary}\t${entry.timestamp}\n"
            )
        } catch (_: Exception) { /* best-effort */ }
    }

    private fun recallFromCold(query: String, maxResults: Int): List<SpanEntry> {
        val results = mutableListOf<SpanEntry>()
        try {
            val file = File(coldDir, "scroll_index.txt")
            if (!file.exists()) return results
            file.forEachLine { line ->
                if (results.size >= maxResults) return@forEachLine
                if (line.lowercase().contains(query)) {
                    val parts = line.split("\t")
                    if (parts.size >= 6) {
                        results.add(SpanEntry(
                            id = parts[0].toIntOrNull() ?: return@forEachLine,
                            seqLo = parts[1].toIntOrNull() ?: 0,
                            seqHi = parts[2].toIntOrNull() ?: 0,
                            headline = parts[3],
                            summary = parts[4],
                            timestamp = parts[5].toLongOrNull() ?: 0L
                        ))
                    }
                }
            }
        } catch (_: Exception) { /* best-effort */ }
        return results
    }

    private fun countColdSpans(): Int {
        try {
            val file = File(coldDir, "scroll_index.txt")
            return if (file.exists()) file.readLines().size else 0
        } catch (_: Exception) { return 0 }
    }

    fun clear() {
        synchronized(index) { index.clear() }
        try { File(coldDir, "scroll_index.txt").delete() } catch (_: Exception) {}
    }
}
