// SPDX-FileCopyrightText: 2026 深圳哇蓝文化科技有限公司 (ShenZhen wowblue culture and technology CO.,LTD.)
// SPDX-License-Identifier: AGPL-3.0-or-later

package com.mengpaw.core

import com.mengpaw.core.agent.AgentDocManager
import com.mengpaw.core.agent.AgentExecutor
import com.mengpaw.core.agent.AgentMiddleware
import com.mengpaw.core.agent.MemoryRecord
import com.mengpaw.core.agent.PostCallMiddleware
import com.mengpaw.core.agent.ScrollContextManager
import com.mengpaw.core.cli.*
import com.mengpaw.core.llm.*
import com.mengpaw.core.namespace.SelfExecutor
import com.mengpaw.core.namespace.SysExecutor
import com.mengpaw.core.plugin.PluginExecutor
import com.mengpaw.core.plugin.PluginManager
import com.mengpaw.core.plugin.PluginMarketplaceClient
import com.mengpaw.core.security.IntegrityGuard
import com.mengpaw.core.security.Sanitizer
import com.mengpaw.core.session.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Represents the current state of the agent execution.
 */
sealed class AgentState {
    data object Idle : AgentState()
    data class Running(val task: String, val step: Int, val maxSteps: Int) : AgentState()
    data class Finished(val result: String) : AgentState()
    data class Error(val message: String) : AgentState()
}

/**
 * A single step in a multi-step task plan.
 */
data class PlanStep(
    val index: Int,
    val description: String,
    val action: String,
    val expectedOutcome: String,
    var status: PlanStepStatus = PlanStepStatus.PENDING
)

enum class PlanStepStatus { PENDING, RUNNING, COMPLETED, FAILED }

/**
 * A multi-step execution plan generated by the agent.
 */
data class TaskPlan(
    val task: String,
    val steps: List<PlanStep>,
    val createdAt: Long = System.currentTimeMillis()
) {
    val totalSteps: Int get() = steps.size
    val completedSteps: Int get() = steps.count { it.status == PlanStepStatus.COMPLETED }
    val isComplete: Boolean get() = steps.all { it.status == PlanStepStatus.COMPLETED }
}

/**
 * Central agent engine that drives the ReAct loop:
 *   Thought → Action → Observation → Thought → ... → Final Answer
 *
 * This is the core orchestration that ties together:
 * - LLM provider (reasoning/decision making)
 * - CLI engine (action execution)
 * - Session management (conversation history)
 * - Security (sanitization)
 */
class AgentEngine(
    private val llmProvider: LlmProvider,
    private val pluginManager: PluginManager = PluginManager(),
    private val sessionManager: SessionManager = SessionManager(),
    private val promptEngine: PromptEngine = PromptEngine(),
    private val agentDocManager: AgentDocManager = AgentDocManager(),
    private val integrityGuard: IntegrityGuard = IntegrityGuard(),
    private val middleware: AgentMiddleware = AgentMiddleware.NoOp,
    private val postCallMiddleware: PostCallMiddleware = PostCallMiddleware.NoOp,
    val scrollContext: ScrollContextManager? = null
) {
    private val _state = MutableStateFlow<AgentState>(AgentState.Idle)
    val state: StateFlow<AgentState> = _state.asStateFlow()

    private val _output = MutableStateFlow<String>("")
    val output: StateFlow<String> = _output.asStateFlow()

    /** Prefix-cache-optimized request builder with stable system prompt. */
    private val llmRequestBuilder = LlmRequestBuilder(systemPrompt = promptEngine.buildSystemPrompt())

    /** Cumulative cache hit tokens from LlmRequestBuilder. */
    val cacheHitTokens: Long get() = llmRequestBuilder.cumulativeCacheHitTokens

    /** Cumulative cache miss tokens from LlmRequestBuilder. */
    val cacheMissTokens: Long get() = llmRequestBuilder.cumulativeCacheMissTokens

    /** Approximate cache hit ratio (0.0–1.0) across all calls. */
    val cacheHitRatio: Double get() {
        val total = cacheHitTokens + cacheMissTokens
        return if (total > 0) cacheHitTokens.toDouble() / total else 0.0
    }

    /** Estimated USD cost saved by cache hits (DeepSeek V4 flash pricing). */
    val estimatedSavingsUsd: Double get() {
        val hit = cacheHitTokens
        // Cache miss = $0.14/1K, Cache hit = $0.0028/1K → save $0.1372/1K tokens
        return hit * 0.0001372
    }

    /** Current cache strategy label for UI display. */
    val cacheStrategyLabel: String get() = CacheStrategy.labelFor(llmRequestBuilder.cacheStrategy)

    /** Auto-configure cache strategy from the LLM provider's endpoint. */
    fun configureCacheStrategy(endpoint: String) {
        llmRequestBuilder.cacheStrategy = CacheStrategy.forProvider(endpoint)
    }

    // ── Context folding (Reasonix-inspired, MIT license) ──
    // Thresholds are ratios of the context window (not absolute tokens),
    // so they adapt to different models automatically.
    private companion object {
        const val SOFT_COMPACT_RATIO = 0.50     // 50% → notify growing, no action
        const val TOOL_SNIP_RATIO = 0.60        // 60% → snip stale tool results first
        const val COMPACT_RATIO = 0.80          // 80% → trigger full compaction
        const val COMPACT_FORCE_RATIO = 0.90    // 90% → force even low-value folds
        const val MIN_FOLD_TOKENS = 400         // skip folds smaller than this (not worth the API call)
        const val DEFAULT_CONTEXT_WINDOW = 131_072  // fallback when model window is unknown
    }

    private var consecutiveCompacts = 0
    private var compactStuck = false

    /**
     * Estimate context usage ratio using calibrated tokPerChar when available,
     * falling back to the hardcoded heuristic.
     */
    private fun estimateContextRatio(promptTokens: Int): Double {
        val window = DEFAULT_CONTEXT_WINDOW.toDouble()
        return promptTokens / window
    }

    /** Estimate tokens for a string using the calibrated ratio. */
    private fun estimateTokens(text: String): Int {
        val ratio = llmRequestBuilder.calibratedTokPerChar
        return (text.length * ratio).toInt()
    }

    /**
     * Snip stale tool results: rewrite old observation messages to short markers.
     * This alone often brings context under the threshold without a full compaction,
     * preserving the prefix cache that would be lost on a summarize API call.
     * @return number of messages snipped
     */
    private fun snipStaleToolResults(sessionId: String, currentStep: Int): Int {
        var count = 0
        val history = sessionManager.getStructuredHistory(sessionId)
        val threshold = currentStep - 3 // steps older than this are "stale"

        history.forEachIndexed { index, msg ->
            if (msg["role"] == "assistant" && threshold > 0) {
                val content = msg["content"] ?: ""
                if (content.startsWith("Command:") && content.length > 120) {
                    // Replace with snipped marker — keeps the message in the array
                    // but drastically reduces its token footprint
                    sessionManager.addMessage(sessionId,
                        Message("system", "[snip — tool result from earlier step compressed]"))
                    count++
                }
            }
        }
        return count
    }

    /**
     * Check whether context folding is needed after an LLM response.
     * Three-stage pipeline: soft notify → snip stale results → full compaction.
     * Includes fold-economics check and stuck-detection per Reasonix compact.go.
     * @return true if folding was performed
     */
    private suspend fun maybeFoldContext(sessionId: String, promptTokens: Int): Boolean {
        if (compactStuck) return false

        val ratio = estimateContextRatio(promptTokens)

        // Stage 0: below 50% — healthy, reset counters
        if (ratio < SOFT_COMPACT_RATIO) {
            consecutiveCompacts = 0
            compactStuck = false
            return false
        }

        // Stage 1: 50%-60% — soft notice, no action (cache stays warm)
        if (ratio < TOOL_SNIP_RATIO) {
            return false
        }

        // Stage 2: 60%-80% — try snipping stale tool results first
        if (ratio < COMPACT_RATIO) {
            val snipped = snipStaleToolResults(sessionId, promptTokens.hashCode() % 50)
            // Snip alone may have brought us under the trigger; no need for full compaction
            return snipped > 0
        }

        // Stage 3: 80%+ — full compaction needed
        // Fold economics: skip if foldable region is too small
        val estimatedFoldTokens = (promptTokens * 0.3).toInt() // rough: ~30% of prompt is foldable
        if (ratio < COMPACT_FORCE_RATIO && estimatedFoldTokens < MIN_FOLD_TOKENS) {
            return false
        }

        // Call session compression
        sessionManager.compressIfNeeded(llmProvider)
        consecutiveCompacts++

        // Stuck detection: if compaction fires twice in a row, the tail alone is too large
        if (consecutiveCompacts >= 2) {
            compactStuck = true
            val msg = when (agentLanguage) {
                PromptEngine.AgentLanguage.CHINESE ->
                    "上下文窗口不足以容纳当前对话。自动折叠已暂停。建议手动清理历史或增大模型的 context_window 设置。"
                PromptEngine.AgentLanguage.ENGLISH ->
                    "Context window too small for current conversation. Auto-compaction paused. Consider clearing history or increasing the model's context_window."
            }
            sessionManager.addMessage(sessionId, Message("system", msg))
        }

        return true
    }

    /** Current Agent language setting. */
    var agentLanguage: PromptEngine.AgentLanguage = PromptEngine.AgentLanguage.CHINESE
        private set

    /** This agent's display name. */
    var agentName: String = "MengPaw"
        private set

    /** Framework this agent belongs to (null = local). */
    var framework: String? = null
        private set

    /** Model name powering this agent. */
    var modelName: String = "unknown"
        private set

    /**
     * Update agent identity and rebuild the system prompt.
     */
    fun setAgentIdentity(name: String, framework: String?, model: String) {
        agentName = name
        this.framework = framework
        this.modelName = model
        rebuildSystemPrompt()
    }

    /**
     * Switch the Agent's thinking/output language.
     * Updates the system prompt and resets prefix cache counters.
     */
    fun setAgentLanguage(lang: PromptEngine.AgentLanguage) {
        if (lang != agentLanguage) {
            agentLanguage = lang
            rebuildSystemPrompt()
        }
    }

    private fun rebuildSystemPrompt() {
        val base = promptEngine.buildSystemPrompt(
            lang = agentLanguage,
            agentName = agentName,
            framework = framework,
            modelName = modelName
        )
        val processed = middleware.onSystemPrompt(base, agentName)
        llmRequestBuilder.updateSystemPrompt(processed)
    }

    /** Plugin marketplace client for plugin.* commands. */
    private val marketplaceClient = PluginMarketplaceClient()

    /** Plugin CLI executor — built-in namespace for plugin management. */
    private val pluginExecutor = PluginExecutor(pluginManager, marketplaceClient)

    /** Agent document executor — built-in namespace for agent docs. */
    private val agentExecutor = AgentExecutor(agentDocManager)

    /**
     * Build a Pipeline dynamically from PluginManager active plugins.
     * "self" and "plugin" namespaces are always registered as built-ins.
     */
    private fun buildPipeline(): Pipeline {
        val registry = CommandRegistry()

        // Built-in: self namespace (Agent introspection — always available)
        registry.registerNamespace("self", SelfExecutor.commands)

        // Built-in: plugin namespace (plugin management — always available)
        registry.registerNamespace("plugin", pluginExecutor.commands)

        // Built-in: agent namespace (agent docs & memory — always available)
        registry.registerNamespace("agent", agentExecutor.commands)

        // Built-in: sys namespace (system info — always available)
        registry.registerNamespace("sys", SysExecutor.commands)

        // Dynamic: register all active plugin commands
        pluginManager.getActivePlugins().forEach { plugin ->
            val ns = plugin.metadata.id
                .removeSuffix("-plugin")
                .removeSuffix("-ext")
            plugin.commands.forEach { (name, handler) ->
                registry.register("$ns.$name", handler)
            }
        }

        // Bind registry so future plugin activations register automatically
        pluginManager.bindRegistry(registry)

        return Pipeline(registry = registry)
    }

    /**
     * A single trace step emitted during ReAct execution.
     */
    data class TraceStep(
        val step: Int,
        val thought: String,
        val action: String?,
        val observation: String?
    )

    /**
     * Run a task through the ReAct loop.
     * @param task The user's task description
     * @param maxSteps Maximum ReAct iterations before forced stop
     * @param onStep Optional callback invoked after each ReAct iteration with trace data
     */
    suspend fun run(task: String, maxSteps: Int = 50, onStep: ((TraceStep) -> Unit)? = null): String {
        val session = sessionManager.createSession(task)
        val context = ExecutionContext(sessionId = session.id)
        _state.value = AgentState.Running(task, 0, maxSteps)
        _output.value = ""

        // Initialize conversation — system prompt injected by buildConversation via LlmRequestBuilder
        sessionManager.addMessage(session.id, Message("user", task))

        try {
            for (step in 0 until maxSteps) {
                _state.value = AgentState.Running(task, step + 1, maxSteps)

                // 1. THINK: Get LLM response (prefix cache anchored by LlmRequestBuilder)
                val conversation = buildConversation(session.id)
                val llmResponse = llmProvider.completeWithMessages(conversation)
                val sanitized = Sanitizer.sanitize(llmResponse)

                // Post-call middleware: trim oversized results, check context health, trigger scroll eviction
                val totalChars = llmRequestBuilder.currentSystemPrompt.length +
                    sessionManager.getStructuredHistory(session.id).sumOf { (it["content"]?.length ?: 0) }
                val estimatedTokens = (totalChars * llmRequestBuilder.calibratedTokPerChar).toInt()
                llmRequestBuilder.lastPromptTokens = estimatedTokens
                llmRequestBuilder.calibrateFromUsage(estimatedTokens, totalChars)

                val postResult = postCallMiddleware.onPostCall(sanitized, step + 1, totalChars, estimatedTokens)

                sessionManager.addMessage(session.id, Message("assistant", postResult.text))
                _output.value = postResult.text

                // Middleware-triggered context folding or scroll eviction
                if (postResult.shouldFold) {
                    // Scroll eviction: index old spans before folding
                    scrollContext?.evictSpan(
                        seqLo = maxOf(0, step - 10),
                        seqHi = step,
                        text = postResult.text.take(6000),
                        headline = postResult.foldReason ?: "Step ${step + 1} context eviction"
                    )
                    maybeFoldContext(session.id, estimatedTokens)
                }

                // 2. PARSE: Extract Thought/Action from LLM output
                val parsed = promptEngine.parse(sanitized)

                // 3. CHECK: Is this the final answer?
                if (parsed.isFinal) {
                    val answer = parsed.thought
                    sessionManager.addMessage(session.id, Message("assistant", answer))
                    _state.value = AgentState.Finished(answer)
                    recordTaskMemory(task, answer)
                    return answer
                }

                // 4. ACT: Execute the command
                if (parsed.action != null) {
                    val commandLine = "${parsed.action.name} ${parsed.action.parameters.values.joinToString(" ")}"

                    // Loop detection
                    if (promptEngine.detectLoop(commandLine)) {
                        val errorMsg = localizedError("loop_detected", commandLine)
                        sessionManager.addMessage(session.id, Message("assistant", errorMsg))
                        _state.value = AgentState.Error(errorMsg)
                        onStep?.invoke(TraceStep(step + 1, parsed.thought, commandLine, errorMsg))
                        return errorMsg
                    }

                    // Execute
                    val result = buildPipeline().execute(commandLine, context)
                    val observation = if (result.success) result.output else "Error: ${result.error}"

                    // Emit trace step
                    onStep?.invoke(TraceStep(step + 1, parsed.thought, commandLine, observation))

                    // Add observation to conversation
                    val observationEntry = "Command: $commandLine\nResult: $observation"
                    sessionManager.addMessage(session.id, Message("assistant", observationEntry))
                } else {
                    // Thought without action — still emit trace
                    onStep?.invoke(TraceStep(step + 1, parsed.thought, null, null))
                }
            }

            // Max steps reached
            val msg = localizedError("max_steps", maxSteps.toString())
            sessionManager.addMessage(session.id, Message("assistant", msg))
            _state.value = AgentState.Finished(msg)
            return msg
        } catch (e: Exception) {
            val errorMsg = localizedError("agent_error", e.message ?: e::class.simpleName ?: "unknown")
            sessionManager.addMessage(session.id, Message("assistant", errorMsg))
            _state.value = AgentState.Error(errorMsg)
            return errorMsg
        }
    }

    /**
     * Produce a localized error message based on the current [agentLanguage].
     */
    private fun localizedError(key: String, detail: String): String = when (agentLanguage) {
        PromptEngine.AgentLanguage.CHINESE -> when (key) {
            "loop_detected" -> "错误：检测到命令循环 — '$detail' 已重复 3+ 次"
            "max_steps" -> "已达到最大步数 ($detail)，未获得最终答案"
            "agent_error" -> "Agent 错误：$detail"
            "no_plan" -> "无法为任务生成计划：$detail"
            else -> detail
        }
        PromptEngine.AgentLanguage.ENGLISH -> when (key) {
            "loop_detected" -> "Error: Detected command loop — '$detail' repeated 3+ times"
            "max_steps" -> "Max steps ($detail) reached without final answer"
            "agent_error" -> "Agent error: $detail"
            "no_plan" -> "Could not generate a plan for: $detail"
            else -> detail
        }
    }

    /**
     * Run a task with pre-planning: first decompose into steps, then
     * execute each step sequentially with its own mini ReAct loop.
     *
     * @param task The complex task to plan and execute
     * @param maxStepsPerPlanStep Max ReAct iterations per plan step (default 5)
     * @return A summary of the full execution with per-step results
     */
    suspend fun runWithPlan(task: String, maxStepsPerPlanStep: Int = 5): String {
        _state.value = AgentState.Running(task, 0, 0)
        _output.value = ""

        // Phase 1: Generate execution plan
        val plan = generatePlan(task)
        if (plan.steps.isEmpty()) {
            val msg = localizedError("no_plan", task)
            _state.value = AgentState.Error(msg)
            return msg
        }

        _output.value = formatPlanSummary(plan)

        // Phase 2: Execute each step
        val results = mutableListOf<String>()
        for (step in plan.steps) {
            step.status = PlanStepStatus.RUNNING
            _state.value = AgentState.Running(
                "[Step ${step.index + 1}/${plan.totalSteps}] ${step.description}",
                step.index + 1,
                plan.totalSteps
            )

            try {
                val stepResult = executePlanStep(step, maxStepsPerPlanStep)
                results.add("[OK] Step ${step.index + 1}: ${stepResult}")
                step.status = PlanStepStatus.COMPLETED
            } catch (e: Exception) {
                val errorMsg = "[FAIL] Step ${step.index + 1}: ${e.message}"
                results.add(errorMsg)
                step.status = PlanStepStatus.FAILED
            }

            val progress = "Progress: ${plan.completedSteps}/${plan.totalSteps} steps done"
            _output.value = "${results.joinToString("\n")}\n$progress"
        }

        // Phase 3: Build summary
        val summary = buildString {
            appendLine("=== Task Plan Execution Complete ===")
            appendLine("Task: ${plan.task}")
            appendLine("Steps: ${plan.completedSteps}/${plan.totalSteps} completed")
            appendLine()
            results.forEach { appendLine(it) }
            val failed = plan.steps.filter { it.status == PlanStepStatus.FAILED }
            if (failed.isNotEmpty()) {
                appendLine()
                appendLine("WARNING: ${failed.size} step(s) failed:")
                failed.forEach { appendLine("  - ${it.description}") }
            }
        }

        _state.value = AgentState.Finished(summary)
        return summary
    }

    /**
     * Generate a structured multi-step execution plan for a task.
     * Uses the LLM to decompose the task, then parses the response.
     */
    suspend fun generatePlan(task: String): TaskPlan {
        val planPrompt = listOf(
            mapOf("role" to "user", "content" to """
                Decompose the following task into a step-by-step execution plan.
                Your response must use ONLY the following format, one step per line:

                STEP <N>: <description> | ACTION: <cli-command> | EXPECT: <expected outcome>

                Rules:
                - Number steps starting from 1
                - Each ACTION must be a single CLI command (e.g. fs.cat /path)
                - Keep the total to 3-7 steps
                - Do NOT include any other text before or after the plan

                Task: $task
            """.trimIndent())
        )

        val response = llmProvider.completeWithMessages(planPrompt)
        return parsePlan(task, response)
    }

    /**
     * Parse a plan text response into a [TaskPlan].
     * Format: STEP <N>: <description> | ACTION: <command> | EXPECT: <outcome>
     */
    private fun parsePlan(task: String, text: String): TaskPlan {
        val stepRegex = Regex(
            """STEP\s*(\d+)\s*:\s*(.+?)\s*\|\s*ACTION\s*:\s*(.+?)\s*\|\s*EXPECT\s*:\s*(.+)""",
            setOf(RegexOption.IGNORE_CASE, RegexOption.MULTILINE)
        )

        val steps = stepRegex.findAll(text).map { match ->
            val (num, desc, action, expected) = match.destructured
            PlanStep(
                index = num.toIntOrNull() ?: 0,
                description = desc.trim(),
                action = action.trim(),
                expectedOutcome = expected.trim()
            )
        }.toList().sortedBy { it.index }

        // Re-index to ensure 0-based
        return TaskPlan(
            task = task,
            steps = steps.mapIndexed { i, s -> s.copy(index = i) }
        )
    }

    /**
     * Execute a single plan step via mini ReAct loop.
     */
    private suspend fun executePlanStep(step: PlanStep, maxSteps: Int): String {
        val stepSession = sessionManager.createSession("PlanStep: ${step.description}")
        val context = ExecutionContext(sessionId = stepSession.id)
        sessionManager.addMessage(stepSession.id, Message("system",
            "Execute this single step: ${step.description}\n" +
            "Planned action: ${step.action}\n" +
            "Expected outcome: ${step.expectedOutcome}"
        ))

        for (iteration in 0 until maxSteps) {
            val conversation = buildConversation(stepSession.id)
            val llmResponse = llmProvider.completeWithMessages(conversation)
            val sanitized = Sanitizer.sanitize(llmResponse)
            sessionManager.addMessage(stepSession.id, Message("assistant", sanitized))

            val parsed = promptEngine.parse(sanitized)
            if (parsed.isFinal) {
                return parsed.thought
            }

            if (parsed.action != null) {
                val cmd = "${parsed.action.name} ${parsed.action.parameters.values.joinToString(" ")}"
                val result = buildPipeline().execute(cmd, context)
                val observation = if (result.success) result.output else "Error: ${result.error}"
                sessionManager.addMessage(stepSession.id, Message("assistant",
                    "Command: $cmd\nResult: $observation"))
            }
        }

        return "Step completed (max iterations reached): ${step.description}"
    }

    private fun formatPlanSummary(plan: TaskPlan): String = buildString {
        appendLine("=== Task Plan ===")
        appendLine("Task: ${plan.task}")
        appendLine("Steps: ${plan.totalSteps}")
        plan.steps.forEach { step ->
            appendLine("  ${step.index + 1}. ${step.description}")
            appendLine("     Action: ${step.action}")
            appendLine("     Expect: ${step.expectedOutcome}")
        }
    }

    /**
     * Stop the current agent execution.
     */
    fun stop() {
        _state.value = AgentState.Idle
    }

    private suspend fun buildConversation(sessionId: String): List<Map<String, String>> {
        sessionManager.compressIfNeeded(llmProvider)
        val history = sessionManager.getStructuredHistory(sessionId)
        // Always inject the stable system prompt via LlmRequestBuilder for prefix-cache optimization.
        // If history already has a system message (e.g. compression summary), skip it to avoid double system.
        val nonSystemHistory = if (history.isNotEmpty() && history[0]["role"] == "system") {
            history.drop(1)
        } else {
            history
        }
        return llmRequestBuilder.buildMessages(nonSystemHistory, injectCacheAnnotations = true)
    }

    private fun buildCommandString(action: ToolCall): String {
        val params = action.parameters.entries.joinToString(" ") { (k, v) -> "--$k $v" }
        return "${action.name} $params"
    }

    /**
     * Auto-record task completion to Agent's Memory.md.
     */
    private fun recordTaskMemory(task: String, result: String) {
        try {
            val entry = MemoryRecord(
                id = "mem-${System.currentTimeMillis().toString().takeLast(6)}",
                date = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm", java.util.Locale.US).format(java.util.Date()),
                title = task.take(60),
                keywords = task.split(" ").filter { it.length > 1 }.take(5),
                content = result.take(500)
            )
            agentDocManager.updateMemory(entry)
        } catch (e: Exception) {
            // Memory recording is best-effort — never block task completion
        }
    }
}
