// SPDX-FileCopyrightText: 2026 MengPaw
// SPDX-License-Identifier: AGPL-3.0-or-later

package com.mengpaw.core

import com.mengpaw.core.agent.AgentDocManager
import com.mengpaw.core.agent.AgentExecutor
import com.mengpaw.core.agent.MemoryRecord
import com.mengpaw.core.cli.*
import com.mengpaw.core.llm.*
import com.mengpaw.core.namespace.SelfExecutor
import com.mengpaw.core.namespace.SysExecutor
import com.mengpaw.core.plugin.PluginExecutor
import com.mengpaw.core.plugin.PluginManager
import com.mengpaw.core.plugin.PluginMarketplaceClient
import com.mengpaw.core.security.IntegrityGuard
import com.mengpaw.core.security.Sanitizer
import com.mengpaw.core.session.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Represents the current state of the agent execution.
 */
sealed class AgentState {
    data object Idle : AgentState()
    data class Running(val task: String, val step: Int, val maxSteps: Int) : AgentState()
    data class Finished(val result: String) : AgentState()
    data class Error(val message: String) : AgentState()
}

/**
 * A single step in a multi-step task plan.
 */
data class PlanStep(
    val index: Int,
    val description: String,
    val action: String,
    val expectedOutcome: String,
    var status: PlanStepStatus = PlanStepStatus.PENDING
)

enum class PlanStepStatus { PENDING, RUNNING, COMPLETED, FAILED }

/**
 * A multi-step execution plan generated by the agent.
 */
data class TaskPlan(
    val task: String,
    val steps: List<PlanStep>,
    val createdAt: Long = System.currentTimeMillis()
) {
    val totalSteps: Int get() = steps.size
    val completedSteps: Int get() = steps.count { it.status == PlanStepStatus.COMPLETED }
    val isComplete: Boolean get() = steps.all { it.status == PlanStepStatus.COMPLETED }
}

/**
 * Central agent engine that drives the ReAct loop:
 *   Thought → Action → Observation → Thought → ... → Final Answer
 *
 * This is the core orchestration that ties together:
 * - LLM provider (reasoning/decision making)
 * - CLI engine (action execution)
 * - Session management (conversation history)
 * - Security (sanitization)
 */
class AgentEngine(
    private val llmProvider: LlmProvider,
    private val pluginManager: PluginManager = PluginManager(),
    private val sessionManager: SessionManager = SessionManager(),
    private val promptEngine: PromptEngine = PromptEngine(),
    private val agentDocManager: AgentDocManager = AgentDocManager(),
    private val integrityGuard: IntegrityGuard = IntegrityGuard()
) {
    private val _state = MutableStateFlow<AgentState>(AgentState.Idle)
    val state: StateFlow<AgentState> = _state.asStateFlow()

    private val _output = MutableStateFlow<String>("")
    val output: StateFlow<String> = _output.asStateFlow()

    /** Prefix-cache-optimized request builder with stable system prompt. */
    private val llmRequestBuilder = LlmRequestBuilder(systemPrompt = promptEngine.buildSystemPrompt())

    /** Cumulative cache hit tokens from LlmRequestBuilder. */
    val cacheHitTokens: Long get() = llmRequestBuilder.cumulativeCacheHitTokens

    /** Cumulative cache miss tokens from LlmRequestBuilder. */
    val cacheMissTokens: Long get() = llmRequestBuilder.cumulativeCacheMissTokens

    /** Current Agent language setting. */
    var agentLanguage: PromptEngine.AgentLanguage = PromptEngine.AgentLanguage.CHINESE
        private set

    /**
     * Switch the Agent's thinking/output language.
     * Updates the system prompt and resets prefix cache counters.
     * Call this when the user changes language preference.
     */
    fun setAgentLanguage(lang: PromptEngine.AgentLanguage) {
        if (lang != agentLanguage) {
            agentLanguage = lang
            llmRequestBuilder.updateSystemPrompt(promptEngine.buildSystemPrompt(lang))
        }
    }

    /** Plugin marketplace client for plugin.* commands. */
    private val marketplaceClient = PluginMarketplaceClient()

    /** Plugin CLI executor — built-in namespace for plugin management. */
    private val pluginExecutor = PluginExecutor(pluginManager, marketplaceClient)

    /** Agent document executor — built-in namespace for agent docs. */
    private val agentExecutor = AgentExecutor(agentDocManager)

    /**
     * Build a Pipeline dynamically from PluginManager active plugins.
     * "self" and "plugin" namespaces are always registered as built-ins.
     */
    private fun buildPipeline(): Pipeline {
        val registry = CommandRegistry()

        // Built-in: self namespace (Agent introspection — always available)
        registry.registerNamespace("self", SelfExecutor.commands)

        // Built-in: plugin namespace (plugin management — always available)
        registry.registerNamespace("plugin", pluginExecutor.commands)

        // Built-in: agent namespace (agent docs & memory — always available)
        registry.registerNamespace("agent", agentExecutor.commands)

        // Built-in: sys namespace (system info — always available)
        registry.registerNamespace("sys", SysExecutor.commands)

        // Dynamic: register all active plugin commands
        pluginManager.getActivePlugins().forEach { plugin ->
            val ns = plugin.metadata.id
                .removeSuffix("-plugin")
                .removeSuffix("-ext")
            plugin.commands.forEach { (name, handler) ->
                registry.register("$ns.$name", handler)
            }
        }

        // Bind registry so future plugin activations register automatically
        pluginManager.bindRegistry(registry)

        return Pipeline(registry = registry)
    }

    /**
     * Run a task through the ReAct loop.
     * @param task The user's task description
     * @param maxSteps Maximum ReAct iterations before forced stop
     */
    suspend fun run(task: String, maxSteps: Int = 50): String {
        val session = sessionManager.createSession(task)
        val context = ExecutionContext(sessionId = session.id)
        _state.value = AgentState.Running(task, 0, maxSteps)
        _output.value = ""

        // Initialize conversation — system prompt injected by buildConversation via LlmRequestBuilder
        sessionManager.addMessage(session.id, Message("user", task))

        try {
            for (step in 0 until maxSteps) {
                _state.value = AgentState.Running(task, step + 1, maxSteps)

                // 1. THINK: Get LLM response
                val conversation = buildConversation(session.id)
                val llmResponse = llmProvider.completeWithMessages(conversation)
                val sanitized = Sanitizer.sanitize(llmResponse)

                sessionManager.addMessage(session.id, Message("assistant", sanitized))
                _output.value = sanitized

                // 2. PARSE: Extract Thought/Action from LLM output
                val parsed = promptEngine.parse(sanitized)

                // 3. CHECK: Is this the final answer?
                if (parsed.isFinal) {
                    val answer = parsed.thought
                    sessionManager.addMessage(session.id, Message("assistant", answer))
                    _state.value = AgentState.Finished(answer)
                    recordTaskMemory(task, answer)
                    return answer
                }

                // 4. ACT: Execute the command
                if (parsed.action != null) {
                    val commandLine = "${parsed.action.name} ${parsed.action.parameters.values.joinToString(" ")}"

                    // Loop detection
                    if (promptEngine.detectLoop(commandLine)) {
                        val errorMsg = "Error: Detected command loop - '$commandLine' repeated 3+ times"
                        sessionManager.addMessage(session.id, Message("assistant", errorMsg))
                        _state.value = AgentState.Error(errorMsg)
                        return errorMsg
                    }

                    // Execute
                    val result = buildPipeline().execute(commandLine, context)
                    val observation = if (result.success) result.output else "Error: ${result.error}"

                    // Add observation to conversation
                    val observationEntry = "Command: $commandLine\nResult: $observation"
                    sessionManager.addMessage(session.id, Message("assistant", observationEntry))
                }
            }

            // Max steps reached
            val msg = "Max steps ($maxSteps) reached without final answer"
            sessionManager.addMessage(session.id, Message("assistant", msg))
            _state.value = AgentState.Finished(msg)
            return msg
        } catch (e: Exception) {
            val errorMsg = "Agent error: ${e.message ?: e::class.simpleName}"
            sessionManager.addMessage(session.id, Message("assistant", errorMsg))
            _state.value = AgentState.Error(errorMsg)
            return errorMsg
        }
    }

    /**
     * Run a task with pre-planning: first decompose into steps, then
     * execute each step sequentially with its own mini ReAct loop.
     *
     * @param task The complex task to plan and execute
     * @param maxStepsPerPlanStep Max ReAct iterations per plan step (default 5)
     * @return A summary of the full execution with per-step results
     */
    suspend fun runWithPlan(task: String, maxStepsPerPlanStep: Int = 5): String {
        _state.value = AgentState.Running(task, 0, 0)
        _output.value = ""

        // Phase 1: Generate execution plan
        val plan = generatePlan(task)
        if (plan.steps.isEmpty()) {
            val msg = "Could not generate a plan for: $task"
            _state.value = AgentState.Error(msg)
            return msg
        }

        _output.value = formatPlanSummary(plan)

        // Phase 2: Execute each step
        val results = mutableListOf<String>()
        for (step in plan.steps) {
            step.status = PlanStepStatus.RUNNING
            _state.value = AgentState.Running(
                "[Step ${step.index + 1}/${plan.totalSteps}] ${step.description}",
                step.index + 1,
                plan.totalSteps
            )

            try {
                val stepResult = executePlanStep(step, maxStepsPerPlanStep)
                results.add("[OK] Step ${step.index + 1}: ${stepResult}")
                step.status = PlanStepStatus.COMPLETED
            } catch (e: Exception) {
                val errorMsg = "[FAIL] Step ${step.index + 1}: ${e.message}"
                results.add(errorMsg)
                step.status = PlanStepStatus.FAILED
            }

            val progress = "Progress: ${plan.completedSteps}/${plan.totalSteps} steps done"
            _output.value = "${results.joinToString("\n")}\n$progress"
        }

        // Phase 3: Build summary
        val summary = buildString {
            appendLine("=== Task Plan Execution Complete ===")
            appendLine("Task: ${plan.task}")
            appendLine("Steps: ${plan.completedSteps}/${plan.totalSteps} completed")
            appendLine()
            results.forEach { appendLine(it) }
            val failed = plan.steps.filter { it.status == PlanStepStatus.FAILED }
            if (failed.isNotEmpty()) {
                appendLine()
                appendLine("WARNING: ${failed.size} step(s) failed:")
                failed.forEach { appendLine("  - ${it.description}") }
            }
        }

        _state.value = AgentState.Finished(summary)
        return summary
    }

    /**
     * Generate a structured multi-step execution plan for a task.
     * Uses the LLM to decompose the task, then parses the response.
     */
    suspend fun generatePlan(task: String): TaskPlan {
        val planPrompt = listOf(
            mapOf("role" to "user", "content" to """
                Decompose the following task into a step-by-step execution plan.
                Your response must use ONLY the following format, one step per line:

                STEP <N>: <description> | ACTION: <cli-command> | EXPECT: <expected outcome>

                Rules:
                - Number steps starting from 1
                - Each ACTION must be a single CLI command (e.g. fs.cat /path)
                - Keep the total to 3-7 steps
                - Do NOT include any other text before or after the plan

                Task: $task
            """.trimIndent())
        )

        val response = llmProvider.completeWithMessages(planPrompt)
        return parsePlan(task, response)
    }

    /**
     * Parse a plan text response into a [TaskPlan].
     * Format: STEP <N>: <description> | ACTION: <command> | EXPECT: <outcome>
     */
    private fun parsePlan(task: String, text: String): TaskPlan {
        val stepRegex = Regex(
            """STEP\s*(\d+)\s*:\s*(.+?)\s*\|\s*ACTION\s*:\s*(.+?)\s*\|\s*EXPECT\s*:\s*(.+)""",
            setOf(RegexOption.IGNORE_CASE, RegexOption.MULTILINE)
        )

        val steps = stepRegex.findAll(text).map { match ->
            val (num, desc, action, expected) = match.destructured
            PlanStep(
                index = num.toIntOrNull() ?: 0,
                description = desc.trim(),
                action = action.trim(),
                expectedOutcome = expected.trim()
            )
        }.toList().sortedBy { it.index }

        // Re-index to ensure 0-based
        return TaskPlan(
            task = task,
            steps = steps.mapIndexed { i, s -> s.copy(index = i) }
        )
    }

    /**
     * Execute a single plan step via mini ReAct loop.
     */
    private suspend fun executePlanStep(step: PlanStep, maxSteps: Int): String {
        val stepSession = sessionManager.createSession("PlanStep: ${step.description}")
        val context = ExecutionContext(sessionId = stepSession.id)
        sessionManager.addMessage(stepSession.id, Message("system",
            "Execute this single step: ${step.description}\n" +
            "Planned action: ${step.action}\n" +
            "Expected outcome: ${step.expectedOutcome}"
        ))

        for (iteration in 0 until maxSteps) {
            val conversation = buildConversation(stepSession.id)
            val llmResponse = llmProvider.completeWithMessages(conversation)
            val sanitized = Sanitizer.sanitize(llmResponse)
            sessionManager.addMessage(stepSession.id, Message("assistant", sanitized))

            val parsed = promptEngine.parse(sanitized)
            if (parsed.isFinal) {
                return parsed.thought
            }

            if (parsed.action != null) {
                val cmd = "${parsed.action.name} ${parsed.action.parameters.values.joinToString(" ")}"
                val result = buildPipeline().execute(cmd, context)
                val observation = if (result.success) result.output else "Error: ${result.error}"
                sessionManager.addMessage(stepSession.id, Message("assistant",
                    "Command: $cmd\nResult: $observation"))
            }
        }

        return "Step completed (max iterations reached): ${step.description}"
    }

    private fun formatPlanSummary(plan: TaskPlan): String = buildString {
        appendLine("=== Task Plan ===")
        appendLine("Task: ${plan.task}")
        appendLine("Steps: ${plan.totalSteps}")
        plan.steps.forEach { step ->
            appendLine("  ${step.index + 1}. ${step.description}")
            appendLine("     Action: ${step.action}")
            appendLine("     Expect: ${step.expectedOutcome}")
        }
    }

    /**
     * Stop the current agent execution.
     */
    fun stop() {
        _state.value = AgentState.Idle
    }

    private suspend fun buildConversation(sessionId: String): List<Map<String, String>> {
        sessionManager.compressIfNeeded(llmProvider)
        val history = sessionManager.getStructuredHistory(sessionId)
        // Always inject the stable system prompt via LlmRequestBuilder for prefix-cache optimization.
        // If history already has a system message (e.g. compression summary), skip it to avoid double system.
        val nonSystemHistory = if (history.isNotEmpty() && history[0]["role"] == "system") {
            history.drop(1)
        } else {
            history
        }
        return llmRequestBuilder.buildMessages(nonSystemHistory)
    }

    private fun buildCommandString(action: ToolCall): String {
        val params = action.parameters.entries.joinToString(" ") { (k, v) -> "--$k $v" }
        return "${action.name} $params"
    }

    /**
     * Auto-record task completion to Agent's Memory.md.
     */
    private fun recordTaskMemory(task: String, result: String) {
        try {
            val entry = MemoryRecord(
                id = "mem-${System.currentTimeMillis().toString().takeLast(6)}",
                date = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm", java.util.Locale.US).format(java.util.Date()),
                title = task.take(60),
                keywords = task.split(" ").filter { it.length > 1 }.take(5),
                content = result.take(500)
            )
            agentDocManager.updateMemory(entry)
        } catch (e: Exception) {
            // Memory recording is best-effort — never block task completion
        }
    }
}
